table bias_audit
	lineageTag: f4673967-777b-4fe5-b8c2-394c22a5f59c

	column Flag
		dataType: string
		lineageTag: 90f1dd24-cb94-4cfb-9914-3205ce234ebe
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column Available
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4ca53549-1644-4524-913f-6efa49179882
		summarizeBy: none
		sourceColumn: Available

		annotation SummarizationSetBy = Automatic

	column TrueCount
		dataType: int64
		formatString: 0
		lineageTag: e4fae5c6-0d3f-44a3-9b95-5fcaf4b1cdda
		summarizeBy: sum
		sourceColumn: TrueCount

		annotation SummarizationSetBy = Automatic

	column UnknownCount
		dataType: int64
		formatString: 0
		lineageTag: b872f984-0fd2-4e8a-bc50-5b171950f832
		summarizeBy: sum
		sourceColumn: UnknownCount

		annotation SummarizationSetBy = Automatic

	partition bias_audit = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Albert Leung\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_workbook.xlsx"), null, true),
				    bias_audit_Sheet = Source{[Item="bias_audit",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(bias_audit_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Flag", type text}, {"Available", type logical}, {"TrueCount", Int64.Type}, {"UnknownCount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

