table bias_audit
	lineageTag: d11d65e2-451f-4465-958d-f4aaa116674b

	column Flag
		dataType: string
		lineageTag: 41adcb85-58f6-4780-a2e7-11e8803b6771
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column Available
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4b9433a6-9cc7-4085-9c0a-25d80cdaf41a
		summarizeBy: none
		sourceColumn: Available

		annotation SummarizationSetBy = Automatic

	column TrueCount
		dataType: int64
		formatString: 0
		lineageTag: b144dc4f-c7e6-4fa1-ac4f-2ac18b33bc59
		summarizeBy: sum
		sourceColumn: TrueCount

		annotation SummarizationSetBy = Automatic

	column UnknownCount
		dataType: int64
		formatString: 0
		lineageTag: d38766c3-63c5-468c-a8bc-46222dff9d40
		summarizeBy: sum
		sourceColumn: UnknownCount

		annotation SummarizationSetBy = Automatic

	partition bias_audit = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "bias_audit", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Flag", type text}, {"Available", type logical}, {"TrueCount", Int64.Type}, {"UnknownCount", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

