table calendar_month_summary
	lineageTag: 1e8fa08c-a9d1-4585-9fdd-8ec5c4545bba

	column Period
		dataType: string
		lineageTag: 713b8fca-e426-491f-a955-886df49dc640
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column CalendarMonth
		dataType: int64
		formatString: 0
		lineageTag: 05dfd794-67dd-425c-aed5-e511302d249e
		summarizeBy: sum
		sourceColumn: CalendarMonth

		annotation SummarizationSetBy = Automatic

	column PermitCount
		dataType: int64
		formatString: 0
		lineageTag: c36e039a-0efc-4f56-bca7-6c2a8f239d19
		summarizeBy: sum
		sourceColumn: PermitCount

		annotation SummarizationSetBy = Automatic

	column MonthCount
		dataType: int64
		formatString: 0
		lineageTag: 605506e5-b5ac-467f-9643-d465543ea9b6
		summarizeBy: sum
		sourceColumn: MonthCount

		annotation SummarizationSetBy = Automatic

	column ExposureDays
		dataType: int64
		formatString: 0
		lineageTag: 19398511-7209-41dc-b43e-09d784eb3dd9
		summarizeBy: sum
		sourceColumn: ExposureDays

		annotation SummarizationSetBy = Automatic

	column DP_Rate30
		dataType: double
		lineageTag: c0f437d1-353b-4508-8992-50c8928cd69e
		summarizeBy: sum
		sourceColumn: DP_Rate30

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CompleteMonthCount
		dataType: int64
		formatString: 0
		lineageTag: a71a4b76-940e-48ff-96f0-35aa16befef8
		summarizeBy: sum
		sourceColumn: CompleteMonthCount

		annotation SummarizationSetBy = Automatic

	column PartialMonthCount
		dataType: int64
		formatString: 0
		lineageTag: 3c141af5-7427-4500-8201-59bb23af1b4a
		summarizeBy: sum
		sourceColumn: PartialMonthCount

		annotation SummarizationSetBy = Automatic

	column UnknownMonthCount
		dataType: int64
		formatString: 0
		lineageTag: 76499996-bae1-4047-99a7-6aa067900330
		summarizeBy: sum
		sourceColumn: UnknownMonthCount

		annotation SummarizationSetBy = Automatic

	column CompleteMonthPermitCount
		dataType: int64
		formatString: 0
		lineageTag: adc0fa19-cf71-4d3b-82c3-69ea0f0a25be
		summarizeBy: sum
		sourceColumn: CompleteMonthPermitCount

		annotation SummarizationSetBy = Automatic

	column MeanCompleteMonthlyCount
		dataType: double
		lineageTag: 34d84752-1e12-4a08-983d-2570a2c54ab1
		summarizeBy: sum
		sourceColumn: MeanCompleteMonthlyCount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition calendar_month_summary = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "calendar_month_summary", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"CalendarMonth", Int64.Type}, {"PermitCount", Int64.Type}, {"MonthCount", Int64.Type}, {"ExposureDays", Int64.Type}, {"DP_Rate30", type number}, {"CompleteMonthCount", Int64.Type}, {"PartialMonthCount", Int64.Type}, {"UnknownMonthCount", Int64.Type}, {"CompleteMonthPermitCount", Int64.Type}, {"MeanCompleteMonthlyCount", type number}}, "en-US")
				in
				  #"Changed column type"

