table community_summary
	lineageTag: e7a6d728-dda1-47bd-8194-019681a06f69

	column Period
		dataType: string
		lineageTag: 8eb8d24a-75b3-4937-89dd-d99d844efb95
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column Community
		dataType: string
		lineageTag: 6c8f6955-986d-4a78-acca-ec4e2bddcb12
		summarizeBy: none
		sourceColumn: Community

		annotation SummarizationSetBy = Automatic

	column IsMissingGeography
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 40ede463-b91d-4b42-a7f5-59911fefeb6c
		summarizeBy: none
		sourceColumn: IsMissingGeography

		annotation SummarizationSetBy = Automatic

	column PermitCount
		dataType: int64
		formatString: 0
		lineageTag: 6c9e67ff-d9cf-477a-a6af-c077dcbca3e0
		summarizeBy: sum
		sourceColumn: PermitCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: fc76e458-ee1e-4005-9589-3e71a18d8210
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column PermitShare
		dataType: double
		lineageTag: aac5acef-736f-42e3-9267-838c6fa3fb41
		summarizeBy: sum
		sourceColumn: PermitShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BaselinePeriod
		dataType: string
		lineageTag: dae56485-c12d-4ebc-97a0-446d31c52d9d
		summarizeBy: none
		sourceColumn: BaselinePeriod

		annotation SummarizationSetBy = Automatic

	column BaselinePermitCount
		dataType: int64
		formatString: 0
		lineageTag: f2a6ed9c-c7d7-4dad-9cdd-6209da0596c1
		summarizeBy: sum
		sourceColumn: BaselinePermitCount

		annotation SummarizationSetBy = Automatic

	column AbsoluteChange
		dataType: string
		lineageTag: 37ca7a47-fb56-4d72-a112-d37496f3fddd
		summarizeBy: none
		sourceColumn: AbsoluteChange

		annotation SummarizationSetBy = Automatic

	column PercentChange
		dataType: string
		lineageTag: b80eb5bc-1db7-454f-984c-6f86d7e18c85
		summarizeBy: none
		sourceColumn: PercentChange

		annotation SummarizationSetBy = Automatic

	column SmallBaselineWarning
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 906cdc2f-5575-4d71-b9fd-434ea098fa06
		summarizeBy: none
		sourceColumn: SmallBaselineWarning

		annotation SummarizationSetBy = Automatic

	partition community_summary = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "community_summary", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"Community", type text}, {"IsMissingGeography", type logical}, {"PermitCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"PermitShare", type number}, {"BaselinePeriod", type text}, {"BaselinePermitCount", Int64.Type}, {"SmallBaselineWarning", type logical}}, "en-US")
				in
				  #"Changed column type"

