table development_permits_20260925_045241
	lineageTag: bfc0fcba-a4c6-4d01-ab11-e7e387b0c216

	column point
		dataType: string
		lineageTag: 98ec8653-e68b-4f83-a591-f7be384e1f4c
		summarizeBy: none
		sourceColumn: point

		annotation SummarizationSetBy = Automatic

	column permitnum
		dataType: string
		lineageTag: c7782cf3-51b1-4c9f-bb8a-a6abe70378ee
		summarizeBy: none
		sourceColumn: permitnum

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: 83955926-90d6-4e93-96c1-34ced11f35d9
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column applicant
		dataType: string
		lineageTag: 81bc7ef2-537c-405e-8dc1-90feffc4f09d
		summarizeBy: none
		sourceColumn: applicant

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: ddfce132-c502-49fc-9a70-b4ef6097934f
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 5aae3b2e-abd6-4cba-9dce-ce4b416e4c0e
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column proposedusecode
		dataType: string
		lineageTag: 99d8894b-63a2-4d86-ba03-6a3c6fe6b9de
		summarizeBy: none
		sourceColumn: proposedusecode

		annotation SummarizationSetBy = Automatic

	column proposedusedescription
		dataType: string
		lineageTag: fb1a119e-8202-4259-911a-0a15a8b3754f
		summarizeBy: none
		sourceColumn: proposedusedescription

		annotation SummarizationSetBy = Automatic

	column permitteddiscretionary
		dataType: string
		lineageTag: ed72f9a7-0608-455a-b870-572494b65def
		summarizeBy: none
		sourceColumn: permitteddiscretionary

		annotation SummarizationSetBy = Automatic

	column landusedistrict
		dataType: string
		lineageTag: 74c2d251-4a10-4c20-9f67-8b12a2642eaa
		summarizeBy: none
		sourceColumn: landusedistrict

		annotation SummarizationSetBy = Automatic

	column landusedistrictdescription
		dataType: string
		lineageTag: 2068f456-a660-45ab-962e-c310e1f25a10
		summarizeBy: none
		sourceColumn: landusedistrictdescription

		annotation SummarizationSetBy = Automatic

	column statuscurrent
		dataType: string
		lineageTag: f2851336-9a31-466e-8ea5-67c67086e169
		summarizeBy: none
		sourceColumn: statuscurrent

		annotation SummarizationSetBy = Automatic

	column applieddate
		dataType: dateTime
		formatString: General Date
		lineageTag: f87ff7ea-6784-49a4-bbe9-03bb8942a9cd
		summarizeBy: none
		sourceColumn: applieddate

		variation Variation
			isDefault
			relationship: 36480e88-fc01-473d-ad4e-17ffd0b900b1
			defaultHierarchy: LocalDateTable_58743b17-c430-4382-92b8-59598bf00d78.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column decisiondate
		dataType: dateTime
		formatString: General Date
		lineageTag: 3bc8f331-e981-4a8c-81b8-b2344aa64e00
		summarizeBy: none
		sourceColumn: decisiondate

		variation Variation
			isDefault
			relationship: 55669dc9-204f-4872-be2b-bd29d8030dd2
			defaultHierarchy: LocalDateTable_5fbc8c37-5a47-4391-a313-80848a6e8eea.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column releasedate
		dataType: dateTime
		formatString: General Date
		lineageTag: e05a8e40-53f4-426f-9db4-71b84107e330
		summarizeBy: none
		sourceColumn: releasedate

		variation Variation
			isDefault
			relationship: 43645a04-5acb-416b-8159-b8fac0a63811
			defaultHierarchy: LocalDateTable_e712b260-5486-4bbb-ba0e-2d64ffa2d0de.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column mustcommencedate
		dataType: dateTime
		formatString: General Date
		lineageTag: 86f754b6-215d-4bc5-87a2-aee49fbd0829
		summarizeBy: none
		sourceColumn: mustcommencedate

		variation Variation
			isDefault
			relationship: e803087d-1fbb-445b-92bc-b43e493009de
			defaultHierarchy: LocalDateTable_f78d6c42-1b30-4159-b3e9-64593276f515.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column decision
		dataType: string
		lineageTag: fb7aa7a6-d7ce-47ef-8831-c9448eb0fe4a
		summarizeBy: none
		sourceColumn: decision

		annotation SummarizationSetBy = Automatic

	column decisionby
		dataType: string
		lineageTag: 181611cb-cab4-48c4-ba78-c07c188ce756
		summarizeBy: none
		sourceColumn: decisionby

		annotation SummarizationSetBy = Automatic

	column communitycode
		dataType: string
		lineageTag: d628d840-7076-401b-a205-474754b6f7f0
		summarizeBy: none
		sourceColumn: communitycode

		annotation SummarizationSetBy = Automatic

	column communityname
		dataType: string
		lineageTag: 1b003303-e6f6-417f-ab59-25501717256e
		summarizeBy: none
		sourceColumn: communityname

		annotation SummarizationSetBy = Automatic

	column ward
		dataType: int64
		formatString: 0
		lineageTag: fff61bb1-1711-4c9a-b1a0-8b590e63faeb
		summarizeBy: sum
		sourceColumn: ward

		annotation SummarizationSetBy = Automatic

	column quadrant
		dataType: string
		lineageTag: 944b877f-b6e4-4ab6-9811-fbc1828feacb
		summarizeBy: none
		sourceColumn: quadrant

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 8a4c04a1-d19a-4d3a-b87a-d58765816ccc
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: ccd9ec08-d5f3-448a-b7b6-cd7823447296
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column locationcount
		dataType: int64
		formatString: 0
		lineageTag: cc5608f5-06e4-42da-8b3b-24767b3c9c95
		summarizeBy: sum
		sourceColumn: locationcount

		annotation SummarizationSetBy = Automatic

	column locationtypes
		dataType: string
		lineageTag: e4f2ad4e-8cd6-4951-bb6f-563965b53696
		summarizeBy: none
		sourceColumn: locationtypes

		annotation SummarizationSetBy = Automatic

	column locationaddresses
		dataType: string
		lineageTag: 4c6b82f0-fafe-493f-9600-33839c18bcc4
		summarizeBy: none
		sourceColumn: locationaddresses

		annotation SummarizationSetBy = Automatic

	column locationsgeojson
		dataType: string
		lineageTag: 456f613d-b794-4cbf-bc7b-bcabffadc8a5
		summarizeBy: none
		sourceColumn: locationsgeojson

		annotation SummarizationSetBy = Automatic

	column locationswkt
		dataType: string
		lineageTag: f605ccea-bfbc-4eb4-9a76-3e28717013e5
		summarizeBy: none
		sourceColumn: locationswkt

		annotation SummarizationSetBy = Automatic

	column canceledrefuseddate
		dataType: dateTime
		formatString: General Date
		lineageTag: 8a5e8edb-c8cb-4391-a3ec-59f6c8bd3691
		summarizeBy: none
		sourceColumn: canceledrefuseddate

		variation Variation
			isDefault
			relationship: b57d84b8-310f-4fab-bbb6-48290d8c38b5
			defaultHierarchy: LocalDateTable_9b8acc0a-0e9c-4410-b894-0ed881251475.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column sdabnumber
		dataType: string
		lineageTag: d6d22b9a-2e8b-4df0-96dd-3f57c9f669ff
		summarizeBy: none
		sourceColumn: sdabnumber

		annotation SummarizationSetBy = Automatic

	column sdabhearingdate
		dataType: string
		lineageTag: 3ff1a989-e4e1-4d42-89fc-bdedc6e7710c
		summarizeBy: none
		sourceColumn: sdabhearingdate

		annotation SummarizationSetBy = Automatic

	column sdabdecision
		dataType: string
		lineageTag: 08c65005-8d72-4545-9f5a-9d97b87d6818
		summarizeBy: none
		sourceColumn: sdabdecision

		annotation SummarizationSetBy = Automatic

	column sdabdecisiondate
		dataType: string
		lineageTag: 699e3d78-0010-4b63-8a83-d7e6b27fd015
		summarizeBy: none
		sourceColumn: sdabdecisiondate

		annotation SummarizationSetBy = Automatic

	partition development_permits_20260925_045241 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Albert Leung\PycharmProjects\Data110_DP_Activity\data\raw\development_permits_20260925_045241.csv"),[Delimiter=",", Columns=34, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"point", type text}, {"permitnum", type text}, {"address", type text}, {"applicant", type text}, {"category", type text}, {"description", type text}, {"proposedusecode", type text}, {"proposedusedescription", type text}, {"permitteddiscretionary", type text}, {"landusedistrict", type text}, {"landusedistrictdescription", type text}, {"statuscurrent", type text}, {"applieddate", type datetime}, {"decisiondate", type datetime}, {"releasedate", type datetime}, {"mustcommencedate", type datetime}, {"decision", type text}, {"decisionby", type text}, {"communitycode", type text}, {"communityname", type text}, {"ward", Int64.Type}, {"quadrant", type text}, {"latitude", type number}, {"longitude", type number}, {"locationcount", Int64.Type}, {"locationtypes", type text}, {"locationaddresses", type text}, {"locationsgeojson", type text}, {"locationswkt", type text}, {"canceledrefuseddate", type datetime}, {"sdabnumber", type text}, {"sdabhearingdate", type text}, {"sdabdecision", type text}, {"sdabdecisiondate", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

