table geography_period_totals
	lineageTag: 566395a7-4c7f-4a46-bba8-0999ffb36c85

	column Period
		dataType: string
		lineageTag: 681d3d08-1465-4b22-85f2-3ea20f1b00cc
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column AllPermitCount
		dataType: int64
		formatString: 0
		lineageTag: 7d9ceea5-5e27-4e7b-add5-6479ff87e64b
		summarizeBy: sum
		sourceColumn: AllPermitCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 3d04c4b5-e21e-4591-840d-740eccafaec1
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column ExcludedCount
		dataType: int64
		formatString: 0
		lineageTag: a9bbfbb2-23ba-482e-9f7c-c78888cc7d30
		summarizeBy: sum
		sourceColumn: ExcludedCount

		annotation SummarizationSetBy = Automatic

	column MissingCommunityCount
		dataType: int64
		formatString: 0
		lineageTag: 60b12361-deab-4940-b112-9e4518d508ea
		summarizeBy: sum
		sourceColumn: MissingCommunityCount

		annotation SummarizationSetBy = Automatic

	column MissingWardCount
		dataType: int64
		formatString: 0
		lineageTag: 51b1ca0d-4ea9-47d0-9340-ecd117fb10cd
		summarizeBy: sum
		sourceColumn: MissingWardCount

		annotation SummarizationSetBy = Automatic

	partition geography_period_totals = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "geography_period_totals", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"AllPermitCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"ExcludedCount", Int64.Type}, {"MissingCommunityCount", Int64.Type}, {"MissingWardCount", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

