table monthly_volume
	lineageTag: c5c19714-4e13-4d64-86f9-03b85c6d326d

	column Period
		dataType: string
		lineageTag: 90573ba0-24e5-4c67-bfce-cddd261505cd
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: 7d94d05f-0fd9-4afc-9f2c-2cb56f519e34
		summarizeBy: none
		sourceColumn: YearMonth

		variation Variation
			isDefault
			relationship: f65fc20f-d397-4bea-8a6e-682d4f715f2b
			defaultHierarchy: LocalDateTable_0f8063da-6cae-42d5-9253-b1dbe4f90433.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column PermitCount
		dataType: int64
		formatString: 0
		lineageTag: a2fc6103-71ac-497c-b90b-b96795c31c69
		summarizeBy: sum
		sourceColumn: PermitCount

		annotation SummarizationSetBy = Automatic

	column AllPermitCount
		dataType: int64
		formatString: 0
		lineageTag: 8f914c76-6958-4b5b-8179-624930468741
		summarizeBy: sum
		sourceColumn: AllPermitCount

		annotation SummarizationSetBy = Automatic

	column ExcludedCount
		dataType: int64
		formatString: 0
		lineageTag: a194d9d2-8c3f-4c3b-b164-8f4c984f83f3
		summarizeBy: sum
		sourceColumn: ExcludedCount

		annotation SummarizationSetBy = Automatic

	column ResidentialShare
		dataType: double
		lineageTag: e354038d-c151-482b-b67f-fbfbdb245048
		summarizeBy: sum
		sourceColumn: ResidentialShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExposureDays
		dataType: int64
		formatString: 0
		lineageTag: 5f9e1c20-c39e-449d-96b7-d45447b0077b
		summarizeBy: sum
		sourceColumn: ExposureDays

		annotation SummarizationSetBy = Automatic

	column IsPartialMonth
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 871ca75a-198b-4c91-9e4a-87c35b1bf993
		summarizeBy: none
		sourceColumn: IsPartialMonth

		annotation SummarizationSetBy = Automatic

	column WindowSource
		dataType: string
		lineageTag: b7107815-c1a5-4fae-850c-3f2d972e5f19
		summarizeBy: none
		sourceColumn: WindowSource

		annotation SummarizationSetBy = Automatic

	column DP_Rate30
		dataType: double
		lineageTag: 48ba2e5c-672a-40c3-8bde-5eb500e48508
		summarizeBy: sum
		sourceColumn: DP_Rate30

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition monthly_volume = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "monthly_volume", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"YearMonth", type datetime}, {"PermitCount", Int64.Type}, {"AllPermitCount", Int64.Type}, {"ExcludedCount", Int64.Type}, {"ResidentialShare", type number}, {"ExposureDays", Int64.Type}, {"IsPartialMonth", type logical}, {"WindowSource", type text}, {"DP_Rate30", type number}}, "en-US")
				in
				  #"Changed column type"

