table partial_seasons
	lineageTag: 7038f579-497e-448e-821a-7589f1d98cbe

	column Period
		dataType: string
		lineageTag: ff000e22-f836-4570-b65b-94407ef6588e
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: string
		lineageTag: c3e1518b-7af1-46bd-afe6-7b5c1868429e
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column SeasonStartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 25942ed7-b421-416b-a517-69256e05def3
		summarizeBy: none
		sourceColumn: SeasonStartDate

		variation Variation
			isDefault
			relationship: e32949a4-b968-416a-a83c-63ec16f080d1
			defaultHierarchy: LocalDateTable_06c8c7e3-fd51-456b-a7f2-5f88ab8a5199.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column SeasonEndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 0a14fc74-d4d6-4571-99fe-eda596942749
		summarizeBy: none
		sourceColumn: SeasonEndDate

		variation Variation
			isDefault
			relationship: 9eaa100b-a4f5-4059-a45e-b7a4bde35e8a
			defaultHierarchy: LocalDateTable_c55b038e-0008-4ee5-95ae-dba0baa216c6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column IsCompleteSeason
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6e5fa14e-89c3-4e0a-a40d-449a5980d460
		summarizeBy: none
		sourceColumn: IsCompleteSeason

		annotation SummarizationSetBy = Automatic

	column ExposureDays
		dataType: int64
		formatString: 0
		lineageTag: 48626771-306d-4544-88be-8fc4d30bc523
		summarizeBy: sum
		sourceColumn: ExposureDays

		annotation SummarizationSetBy = Automatic

	column WindowSource
		dataType: string
		lineageTag: a1548b16-7b4d-4881-8347-fb13708d1f7f
		summarizeBy: none
		sourceColumn: WindowSource

		annotation SummarizationSetBy = Automatic

	column PermitCount
		dataType: int64
		formatString: 0
		lineageTag: 9418a056-5acb-46f6-829c-45aed6d5ae9a
		summarizeBy: sum
		sourceColumn: PermitCount

		annotation SummarizationSetBy = Automatic

	column AllPermitCount
		dataType: int64
		formatString: 0
		lineageTag: 4c16de52-6c67-4c20-b080-15bc32bcf39d
		summarizeBy: sum
		sourceColumn: AllPermitCount

		annotation SummarizationSetBy = Automatic

	column ExcludedCount
		dataType: int64
		formatString: 0
		lineageTag: 7cbfe0a9-331d-45d5-965c-09c8cdbb52ad
		summarizeBy: sum
		sourceColumn: ExcludedCount

		annotation SummarizationSetBy = Automatic

	column TotalCount
		dataType: int64
		formatString: 0
		lineageTag: 16d7233a-e66d-48a5-a2d9-56fa7ac90a11
		summarizeBy: sum
		sourceColumn: TotalCount

		annotation SummarizationSetBy = Automatic

	column ValidCount
		dataType: int64
		formatString: 0
		lineageTag: a9b21bd0-3dd9-4718-8826-eba8b7dd84f8
		summarizeBy: sum
		sourceColumn: ValidCount

		annotation SummarizationSetBy = Automatic

	column InvalidCount
		dataType: int64
		formatString: 0
		lineageTag: 818386dc-8604-4847-9297-bd329f32277e
		summarizeBy: sum
		sourceColumn: InvalidCount

		annotation SummarizationSetBy = Automatic

	column PendingCount
		dataType: int64
		formatString: 0
		lineageTag: 2ce498b8-6aac-4528-805c-dd192d45768b
		summarizeBy: sum
		sourceColumn: PendingCount

		annotation SummarizationSetBy = Automatic

	column RightCensoredCount
		dataType: int64
		formatString: 0
		lineageTag: 8b76f316-d4bc-4cbe-ba83-07c7afbb1a6a
		summarizeBy: sum
		sourceColumn: RightCensoredCount

		annotation SummarizationSetBy = Automatic

	column ValidShare
		dataType: double
		lineageTag: b5f14d4b-7319-4397-8323-2a8d9986d11d
		summarizeBy: sum
		sourceColumn: ValidShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NegativeCount
		dataType: int64
		formatString: 0
		lineageTag: 3265ea85-5968-41ae-84f1-da85d853a9e9
		summarizeBy: sum
		sourceColumn: NegativeCount

		annotation SummarizationSetBy = Automatic

	column MissingDateCount
		dataType: int64
		formatString: 0
		lineageTag: e4f3ed48-6997-4c84-9957-bee6be357c1b
		summarizeBy: sum
		sourceColumn: MissingDateCount

		annotation SummarizationSetBy = Automatic

	column InvalidDateCount
		dataType: int64
		formatString: 0
		lineageTag: 1e94e9a8-e0d4-4d32-9985-38ce9c5bc0ad
		summarizeBy: sum
		sourceColumn: InvalidDateCount

		annotation SummarizationSetBy = Automatic

	column AfterObservationEndCount
		dataType: int64
		formatString: 0
		lineageTag: 27229b8f-1cff-4d32-ae58-e42c9e3c6eaa
		summarizeBy: sum
		sourceColumn: AfterObservationEndCount

		annotation SummarizationSetBy = Automatic

	column MedianProcessingDays
		dataType: double
		lineageTag: b83fb065-c953-4567-b176-d04ece40ec07
		summarizeBy: sum
		sourceColumn: MedianProcessingDays

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MeanProcessingDays
		dataType: double
		lineageTag: 93163ad7-12e2-4577-903c-631c50e68ea9
		summarizeBy: sum
		sourceColumn: MeanProcessingDays

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Q1ProcessingDays
		dataType: double
		lineageTag: e3a21677-5ae4-469d-87f5-b55599f88fd4
		summarizeBy: sum
		sourceColumn: Q1ProcessingDays

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Q3ProcessingDays
		dataType: double
		lineageTag: 688f7ad8-e0e3-45d3-8848-b269d965f0f8
		summarizeBy: sum
		sourceColumn: Q3ProcessingDays

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IQRProcessingDays
		dataType: double
		lineageTag: a51a9acd-acdd-457a-893a-9b9845a809ea
		summarizeBy: sum
		sourceColumn: IQRProcessingDays

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DP_Rate30
		dataType: double
		lineageTag: d5e38900-55c5-453c-a096-90db07e66e61
		summarizeBy: sum
		sourceColumn: DP_Rate30

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition partial_seasons = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "partial_seasons", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"Season", type text}, {"SeasonStartDate", type datetime}, {"SeasonEndDate", type datetime}, {"IsCompleteSeason", type logical}, {"ExposureDays", Int64.Type}, {"WindowSource", type text}, {"PermitCount", Int64.Type}, {"AllPermitCount", Int64.Type}, {"ExcludedCount", Int64.Type}, {"TotalCount", Int64.Type}, {"ValidCount", Int64.Type}, {"InvalidCount", Int64.Type}, {"PendingCount", Int64.Type}, {"RightCensoredCount", Int64.Type}, {"ValidShare", type number}, {"NegativeCount", Int64.Type}, {"MissingDateCount", Int64.Type}, {"InvalidDateCount", Int64.Type}, {"AfterObservationEndCount", Int64.Type}, {"MedianProcessingDays", type number}, {"MeanProcessingDays", type number}, {"Q1ProcessingDays", type number}, {"Q3ProcessingDays", type number}, {"IQRProcessingDays", type number}, {"DP_Rate30", type number}}, "en-US")
				in
				  #"Changed column type"

