table permits_clean
	lineageTag: 0effdc6f-8f1e-45ea-8df1-89d589effbd1

	column point
		dataType: string
		lineageTag: 70143fe0-1cc8-4083-8118-822bded3c8fa
		summarizeBy: none
		sourceColumn: point

		annotation SummarizationSetBy = Automatic

	column permit_number
		dataType: string
		lineageTag: 14cf8665-5631-456f-a12f-783149a18ec3
		summarizeBy: none
		sourceColumn: permit_number

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: 10576716-09da-4673-bf4a-977ee9e39a39
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column applicant
		dataType: string
		lineageTag: 07f67c64-2407-446f-b6aa-3e1c9fc30813
		summarizeBy: none
		sourceColumn: applicant

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 9c33acc3-4814-4a58-9ee8-4efaed19d3eb
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 56b45868-2615-47d5-bfa1-59b6b953742c
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column proposed_use_code
		dataType: string
		lineageTag: 30458764-9d21-47ae-a545-aef8d4a31771
		summarizeBy: none
		sourceColumn: proposed_use_code

		annotation SummarizationSetBy = Automatic

	column proposed_use_description
		dataType: string
		lineageTag: d6ef8434-6e2a-46aa-acc3-15577e9bcd45
		summarizeBy: none
		sourceColumn: proposed_use_description

		annotation SummarizationSetBy = Automatic

	column permitteddiscretionary
		dataType: string
		lineageTag: 962e2100-3c7c-49dd-b6e2-2076ceef7555
		summarizeBy: none
		sourceColumn: permitteddiscretionary

		annotation SummarizationSetBy = Automatic

	column land_use_district
		dataType: string
		lineageTag: 57e889c3-73c5-4655-9ccf-e13760a4977f
		summarizeBy: none
		sourceColumn: land_use_district

		annotation SummarizationSetBy = Automatic

	column landusedistrictdescription
		dataType: string
		lineageTag: 531546f1-6b58-4650-b06c-d9f7a8051876
		summarizeBy: none
		sourceColumn: landusedistrictdescription

		annotation SummarizationSetBy = Automatic

	column statuscurrent
		dataType: string
		lineageTag: 561fd879-1c83-434b-8f63-5ca3d65fede0
		summarizeBy: none
		sourceColumn: statuscurrent

		annotation SummarizationSetBy = Automatic

	column applied_date
		dataType: dateTime
		formatString: 2001-03 (yyyy-mmm)
		lineageTag: 50f5729f-3937-44d3-bbd4-8b041db585bf
		summarizeBy: none
		sourceColumn: applied_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column decision_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f8a08906-2eaa-46ae-b59e-79b4fcf14617
		summarizeBy: none
		sourceColumn: decision_date

		variation Variation
			isDefault
			relationship: 05d254ad-c56e-45dc-85af-66ef87a1f02c
			defaultHierarchy: LocalDateTable_d9de51cd-7c55-4d9a-b0fd-bff751b79f8e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column releasedate
		dataType: dateTime
		formatString: General Date
		lineageTag: acd7d950-0dc2-4385-b02e-b288a6e5fd3a
		summarizeBy: none
		sourceColumn: releasedate

		variation Variation
			isDefault
			relationship: 7a05f371-d9e4-48c8-9b7e-d07fcdcaee54
			defaultHierarchy: LocalDateTable_74a024e0-d3af-4ca4-9c32-d9feab04791d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column mustcommencedate
		dataType: dateTime
		formatString: General Date
		lineageTag: eafd2887-102c-4d26-a6f4-2acb8113afe1
		summarizeBy: none
		sourceColumn: mustcommencedate

		variation Variation
			isDefault
			relationship: a37c86e6-aabe-4c9b-93fd-deafa6177bed
			defaultHierarchy: LocalDateTable_b856d493-2d08-4c9f-980e-cbc320fa9f16.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column decision
		dataType: string
		lineageTag: 737aa3fa-62fe-4cf0-9f7e-35701e4fcb91
		summarizeBy: none
		sourceColumn: decision

		annotation SummarizationSetBy = Automatic

	column decisionby
		dataType: string
		lineageTag: 025b8928-b19e-4350-b036-0fc83c531a4b
		summarizeBy: none
		sourceColumn: decisionby

		annotation SummarizationSetBy = Automatic

	column communitycode
		dataType: string
		lineageTag: 785976d0-b5a3-4014-a30a-8482d8d3d5fe
		summarizeBy: none
		sourceColumn: communitycode

		annotation SummarizationSetBy = Automatic

	column community
		dataType: string
		lineageTag: 846e220a-ef50-4791-8eb6-b16e742ff56b
		summarizeBy: none
		sourceColumn: community

		annotation SummarizationSetBy = Automatic

	column ward
		dataType: int64
		formatString: 0
		lineageTag: fbe2c294-d5ba-4308-addf-92286c9d0ce6
		summarizeBy: none
		sourceColumn: ward

		annotation SummarizationSetBy = User

	column quadrant
		dataType: string
		lineageTag: 04edcae4-fc6b-4bd7-b199-a6a4037eb346
		summarizeBy: none
		sourceColumn: quadrant

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 7d153812-a259-4c1c-b1ff-e4dd12b15435
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: e12d9257-0a4c-41a4-a6b0-69c1f7297ee4
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column locationcount
		dataType: int64
		formatString: 0
		lineageTag: ba8d008a-8a6b-4202-b77c-7d601562d0fe
		summarizeBy: sum
		sourceColumn: locationcount

		annotation SummarizationSetBy = Automatic

	column locationtypes
		dataType: string
		lineageTag: 74599b6e-7a05-4b26-bdd9-512bf538e2ca
		summarizeBy: none
		sourceColumn: locationtypes

		annotation SummarizationSetBy = Automatic

	column locationaddresses
		dataType: string
		lineageTag: caa45af6-b869-4858-a601-cfa570543738
		summarizeBy: none
		sourceColumn: locationaddresses

		annotation SummarizationSetBy = Automatic

	column locationsgeojson
		dataType: string
		lineageTag: a32c7525-94d6-435a-996f-2a083a684843
		summarizeBy: none
		sourceColumn: locationsgeojson

		annotation SummarizationSetBy = Automatic

	column locationswkt
		dataType: string
		lineageTag: e9b24df2-b008-4792-ab61-356defb55a91
		summarizeBy: none
		sourceColumn: locationswkt

		annotation SummarizationSetBy = Automatic

	column canceledrefuseddate
		dataType: dateTime
		formatString: General Date
		lineageTag: 8b85672e-55c1-44ef-b9e7-e48bca846a3f
		summarizeBy: none
		sourceColumn: canceledrefuseddate

		variation Variation
			isDefault
			relationship: bcbf1c58-0f2b-4160-b95e-cc367fba1a85
			defaultHierarchy: LocalDateTable_edd433d3-7a98-4184-9795-ecb6e206898d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column sdabnumber
		dataType: string
		lineageTag: a6f9bcd1-5369-4175-97cb-38e5c182686d
		summarizeBy: none
		sourceColumn: sdabnumber

		annotation SummarizationSetBy = Automatic

	column sdabhearingdate
		dataType: string
		lineageTag: 23bfc181-7ace-421d-9ea4-c93d3093f28c
		summarizeBy: none
		sourceColumn: sdabhearingdate

		annotation SummarizationSetBy = Automatic

	column sdabdecision
		dataType: string
		lineageTag: cf9fe969-b58e-43ca-ac70-cac9ff3f43e6
		summarizeBy: none
		sourceColumn: sdabdecision

		annotation SummarizationSetBy = Automatic

	column sdabdecisiondate
		dataType: string
		lineageTag: eae02e52-8e05-4d63-b355-23e2c7a6468f
		summarizeBy: none
		sourceColumn: sdabdecisiondate

		annotation SummarizationSetBy = Automatic

	column raw_point
		dataType: string
		lineageTag: 701a11a8-778f-41ef-bf4f-7d05a39e2e33
		summarizeBy: none
		sourceColumn: raw_point

		annotation SummarizationSetBy = Automatic

	column raw_permit_number
		dataType: string
		lineageTag: a5982ab2-e100-470c-a3b3-ece7a5656bb5
		summarizeBy: none
		sourceColumn: raw_permit_number

		annotation SummarizationSetBy = Automatic

	column raw_address
		dataType: string
		lineageTag: b7ede3f9-7311-4e76-b107-f9d693cf6584
		summarizeBy: none
		sourceColumn: raw_address

		annotation SummarizationSetBy = Automatic

	column raw_applicant
		dataType: string
		lineageTag: 6709c796-c9bb-41bf-9b67-850bd6caede6
		summarizeBy: none
		sourceColumn: raw_applicant

		annotation SummarizationSetBy = Automatic

	column raw_category
		dataType: string
		lineageTag: da03b792-7c94-4678-879a-3cc2493e5e2a
		summarizeBy: none
		sourceColumn: raw_category

		annotation SummarizationSetBy = Automatic

	column raw_description
		dataType: string
		lineageTag: 4a6b0098-51fb-4096-a7cd-d78c1d19c3f0
		summarizeBy: none
		sourceColumn: raw_description

		annotation SummarizationSetBy = Automatic

	column raw_proposed_use_code
		dataType: string
		lineageTag: f92851ae-7089-4445-ad53-4772cbe9e889
		summarizeBy: none
		sourceColumn: raw_proposed_use_code

		annotation SummarizationSetBy = Automatic

	column raw_proposed_use_description
		dataType: string
		lineageTag: d3745248-3ece-44bd-a8f4-b3e80e4caf31
		summarizeBy: none
		sourceColumn: raw_proposed_use_description

		annotation SummarizationSetBy = Automatic

	column raw_permitteddiscretionary
		dataType: string
		lineageTag: 4ceb77c7-0c34-400a-9287-709bfd41e8e1
		summarizeBy: none
		sourceColumn: raw_permitteddiscretionary

		annotation SummarizationSetBy = Automatic

	column raw_land_use_district
		dataType: string
		lineageTag: 8995d23f-e3e2-48c8-8f06-a49ddf3ab2bc
		summarizeBy: none
		sourceColumn: raw_land_use_district

		annotation SummarizationSetBy = Automatic

	column raw_landusedistrictdescription
		dataType: string
		lineageTag: afe9ea33-5c77-48c1-a344-4f3787e65053
		summarizeBy: none
		sourceColumn: raw_landusedistrictdescription

		annotation SummarizationSetBy = Automatic

	column raw_statuscurrent
		dataType: string
		lineageTag: cd3689f8-9159-45f3-8686-73cc64c5e020
		summarizeBy: none
		sourceColumn: raw_statuscurrent

		annotation SummarizationSetBy = Automatic

	column raw_applied_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 12e29339-0cf9-4844-96ed-db830a87faa9
		summarizeBy: none
		sourceColumn: raw_applied_date

		variation Variation
			isDefault
			relationship: 7ac6d2ed-78cc-4580-88bc-ba43188014da
			defaultHierarchy: LocalDateTable_9f4d4eb3-deed-4c0f-b8fd-99fd3db498ca.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column raw_decision_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 48275c62-a8eb-4bf7-90dd-8b7571f51a2b
		summarizeBy: none
		sourceColumn: raw_decision_date

		variation Variation
			isDefault
			relationship: c38da3d4-b7ee-4bdf-9619-a1508db6d15c
			defaultHierarchy: LocalDateTable_5c0ce079-0706-4aff-9a29-ac893d1a2abb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column raw_releasedate
		dataType: dateTime
		formatString: General Date
		lineageTag: 3521736b-ee34-4338-af65-945dde790dba
		summarizeBy: none
		sourceColumn: raw_releasedate

		variation Variation
			isDefault
			relationship: 8d02a3b0-125b-4a00-8fbd-a358ed759ff9
			defaultHierarchy: LocalDateTable_0ae4a425-eef9-40fd-9680-501a584b8871.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column raw_mustcommencedate
		dataType: dateTime
		formatString: General Date
		lineageTag: 40b9e870-7713-4700-ac81-841f6fd655a4
		summarizeBy: none
		sourceColumn: raw_mustcommencedate

		variation Variation
			isDefault
			relationship: 592437e2-c5e8-407f-8fdc-b7003935df0b
			defaultHierarchy: LocalDateTable_c19ec3dc-5af0-47a6-a743-0e862218e183.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column raw_decision
		dataType: string
		lineageTag: b67a0289-1ad8-4cdb-94f9-bdb38afe83ab
		summarizeBy: none
		sourceColumn: raw_decision

		annotation SummarizationSetBy = Automatic

	column raw_decisionby
		dataType: string
		lineageTag: b7cd5dc7-69b4-4da6-89dd-9c706229b129
		summarizeBy: none
		sourceColumn: raw_decisionby

		annotation SummarizationSetBy = Automatic

	column raw_communitycode
		dataType: string
		lineageTag: 64281726-d05e-47dd-a896-f1d392f31e9e
		summarizeBy: none
		sourceColumn: raw_communitycode

		annotation SummarizationSetBy = Automatic

	column raw_community
		dataType: string
		lineageTag: c748b770-2de2-42a7-ba13-4a1f5cf0aec0
		summarizeBy: none
		sourceColumn: raw_community

		annotation SummarizationSetBy = Automatic

	column raw_ward
		dataType: int64
		formatString: 0
		lineageTag: 91c1bee5-8dde-45f0-b69c-c5461d6595c5
		summarizeBy: sum
		sourceColumn: raw_ward

		annotation SummarizationSetBy = Automatic

	column raw_quadrant
		dataType: string
		lineageTag: 5dcb99d6-c58f-4172-83d3-093a5772f1ee
		summarizeBy: none
		sourceColumn: raw_quadrant

		annotation SummarizationSetBy = Automatic

	column raw_latitude
		dataType: double
		lineageTag: 40a28d73-28f1-4a0f-ada0-ccb5ec9d469a
		summarizeBy: sum
		sourceColumn: raw_latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column raw_longitude
		dataType: double
		lineageTag: 8f6033c3-6255-484b-845f-45c275e0a8a7
		summarizeBy: sum
		sourceColumn: raw_longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column raw_locationcount
		dataType: int64
		formatString: 0
		lineageTag: 0a40344a-4747-4bd5-a24c-fcd56021ab9e
		summarizeBy: sum
		sourceColumn: raw_locationcount

		annotation SummarizationSetBy = Automatic

	column raw_locationtypes
		dataType: string
		lineageTag: 384c294b-9be8-4232-9273-a8ec597012dd
		summarizeBy: none
		sourceColumn: raw_locationtypes

		annotation SummarizationSetBy = Automatic

	column raw_locationaddresses
		dataType: string
		lineageTag: 04610576-50d0-4f81-9d31-01e7dc7386d3
		summarizeBy: none
		sourceColumn: raw_locationaddresses

		annotation SummarizationSetBy = Automatic

	column raw_locationsgeojson
		dataType: string
		lineageTag: c8c03a82-0518-4b54-b500-4386e0cbd5b9
		summarizeBy: none
		sourceColumn: raw_locationsgeojson

		annotation SummarizationSetBy = Automatic

	column raw_locationswkt
		dataType: string
		lineageTag: bff30b8d-8a33-4036-84ac-fca793aacd2b
		summarizeBy: none
		sourceColumn: raw_locationswkt

		annotation SummarizationSetBy = Automatic

	column raw_canceledrefuseddate
		dataType: dateTime
		formatString: General Date
		lineageTag: fee09aca-b5b7-47fc-8266-419b0b50b5ad
		summarizeBy: none
		sourceColumn: raw_canceledrefuseddate

		variation Variation
			isDefault
			relationship: 7330bc3f-1f6a-40a0-8205-bc85b6df3fa8
			defaultHierarchy: LocalDateTable_f73b96a4-96ca-427f-ae41-83c957c98289.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column raw_sdabnumber
		dataType: string
		lineageTag: 5c9712ec-b3fc-471d-8867-4bf328732c1f
		summarizeBy: none
		sourceColumn: raw_sdabnumber

		annotation SummarizationSetBy = Automatic

	column raw_sdabhearingdate
		dataType: string
		lineageTag: 9fd09868-fbd0-4363-8730-cda8b1ef7280
		summarizeBy: none
		sourceColumn: raw_sdabhearingdate

		annotation SummarizationSetBy = Automatic

	column raw_sdabdecision
		dataType: string
		lineageTag: 6b5e03f1-ca86-4106-9ade-c132d600dd4b
		summarizeBy: none
		sourceColumn: raw_sdabdecision

		annotation SummarizationSetBy = Automatic

	column raw_sdabdecisiondate
		dataType: string
		lineageTag: b9c041c1-edaa-44e9-add2-75e96859d682
		summarizeBy: none
		sourceColumn: raw_sdabdecisiondate

		annotation SummarizationSetBy = Automatic

	column applied_date_invalid
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: da1f92c5-f5db-42d3-96a0-55e16bc7ed2d
		summarizeBy: none
		sourceColumn: applied_date_invalid

		annotation SummarizationSetBy = Automatic

	column decision_date_invalid
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d770df76-16b7-4e88-ac62-e733fd5a0a3d
		summarizeBy: none
		sourceColumn: decision_date_invalid

		annotation SummarizationSetBy = Automatic

	column latitude_invalid
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 678f5297-354e-4a7b-95d7-00a37330ed06
		summarizeBy: none
		sourceColumn: latitude_invalid

		annotation SummarizationSetBy = Automatic

	column longitude_invalid
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ca96989a-55f4-4750-a71d-bcc87e2fc4f4
		summarizeBy: none
		sourceColumn: longitude_invalid

		annotation SummarizationSetBy = Automatic

	column ClassificationRule
		dataType: string
		lineageTag: 769955f3-e616-480c-8f8c-ab907959ba19
		summarizeBy: none
		sourceColumn: ClassificationRule

		annotation SummarizationSetBy = Automatic

	column ValidationStatus
		dataType: string
		lineageTag: 1688e1ec-b459-4d93-ad56-b72ff5768f25
		summarizeBy: none
		sourceColumn: ValidationStatus

		annotation SummarizationSetBy = Automatic

	column IncludeResidential
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 137cba0e-1ef2-4d65-a260-83d5be8f436b
		summarizeBy: none
		sourceColumn: IncludeResidential

		annotation SummarizationSetBy = Automatic

	column ResidentialType
		dataType: string
		lineageTag: c8ff8d1c-e0cc-4bf8-b247-c5a4271877dd
		summarizeBy: none
		sourceColumn: ResidentialType

		annotation SummarizationSetBy = Automatic

	column RezoningRelevant
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a8e6f1d3-ee2e-4436-bebc-3bfe5b6b32bd
		summarizeBy: none
		sourceColumn: RezoningRelevant

		annotation SummarizationSetBy = Automatic

	column ClassificationNeedsReview
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f66b9c55-49d4-4be0-b255-c249786bd961
		summarizeBy: none
		sourceColumn: ClassificationNeedsReview

		annotation SummarizationSetBy = Automatic

	column ClassificationMatchCount
		dataType: int64
		formatString: 0
		lineageTag: cdb4d98d-aa70-4d84-8197-8dc735e435fa
		summarizeBy: sum
		sourceColumn: ClassificationMatchCount

		annotation SummarizationSetBy = Automatic

	column ClassificationConflictCount
		dataType: int64
		formatString: 0
		lineageTag: 078bd7d4-ff3f-4233-8ef2-caaf6deddc64
		summarizeBy: sum
		sourceColumn: ClassificationConflictCount

		annotation SummarizationSetBy = Automatic

	column ClassificationMatchedRules
		dataType: string
		lineageTag: 5c7bc709-6561-4fa2-b45e-d784ee9c4544
		summarizeBy: none
		sourceColumn: ClassificationMatchedRules

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: 483ff31e-6bae-4212-8ce0-fc4b6adcb41c
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column DecisionPeriod
		dataType: string
		lineageTag: 9a514685-345e-4571-ad31-fef1b77c138b
		summarizeBy: none
		sourceColumn: DecisionPeriod

		annotation SummarizationSetBy = Automatic

	column PeriodSortKey
		dataType: int64
		formatString: 0
		lineageTag: 42e5c258-97ef-4f98-810a-5b3e75fefc85
		summarizeBy: count
		sourceColumn: PeriodSortKey

		annotation SummarizationSetBy = Automatic

	column PeriodDateMissing
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0903abbd-e029-4127-9b84-5abde332d3fb
		summarizeBy: none
		sourceColumn: PeriodDateMissing

		annotation SummarizationSetBy = Automatic

	column PeriodDateInvalid
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cea9e9b5-f8d4-4bd3-95e2-bfbf32c0b8fd
		summarizeBy: none
		sourceColumn: PeriodDateInvalid

		annotation SummarizationSetBy = Automatic

	column CrossesPeriodBoundary
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d0aebf1f-fe82-41a4-846c-298dfbf2c4e4
		summarizeBy: none
		sourceColumn: CrossesPeriodBoundary

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: string
		lineageTag: 122207e0-ba8f-49f7-a846-f7808f2b59db
		summarizeBy: none
		sourceColumn: Season
		sortByColumn: 'Season Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column SeasonStartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 6a764a46-f5b1-49aa-9fc9-7f613671bdbb
		summarizeBy: none
		sourceColumn: SeasonStartDate

		variation Variation
			isDefault
			relationship: 6382b765-ece0-4a40-b3dd-88ca87352dcd
			defaultHierarchy: LocalDateTable_7fb1a6f5-720b-4c5b-bb85-deac06f60921.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column SeasonEndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 5f1c486a-d2c0-41ef-863a-ed536e7b2052
		summarizeBy: none
		sourceColumn: SeasonEndDate

		variation Variation
			isDefault
			relationship: fba6ac4a-a45e-4885-8486-166d18455127
			defaultHierarchy: LocalDateTable_01d57250-013e-49fb-8217-b0a51ebc1971.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column SeasonLabel
		dataType: string
		lineageTag: 29920529-138b-4911-b418-b8d42497cc4c
		summarizeBy: none
		sourceColumn: SeasonLabel

		annotation SummarizationSetBy = Automatic

	column SeasonSortKey
		dataType: int64
		formatString: 0
		lineageTag: f66f1551-dd0e-4846-8b36-4ce60b47cf80
		summarizeBy: count
		sourceColumn: SeasonSortKey

		annotation SummarizationSetBy = Automatic

	column IsCompleteSeason
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5dee678d-5d03-42af-96ef-afe98edb7e94
		summarizeBy: none
		sourceColumn: IsCompleteSeason

		annotation SummarizationSetBy = Automatic

	column IsPartialSeason
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4a4b47e6-64b0-482f-b076-6bb9b1e1558a
		summarizeBy: none
		sourceColumn: IsPartialSeason

		annotation SummarizationSetBy = Automatic

	column ProcessingDays
		dataType: int64
		formatString: 0
		lineageTag: 2df036f4-aa3f-488e-bd85-a104c20456ce
		summarizeBy: none
		sourceColumn: ProcessingDays

		annotation SummarizationSetBy = User

	column HasValidProcessingDays
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 16903d77-f522-421b-bda5-5837b50977a1
		summarizeBy: none
		sourceColumn: HasValidProcessingDays

		annotation SummarizationSetBy = Automatic

	column HasNegativeProcessingDays
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 07df3555-a939-4642-8751-0a54830af011
		summarizeBy: none
		sourceColumn: HasNegativeProcessingDays

		annotation SummarizationSetBy = Automatic

	column IsPending
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fc90546d-07c4-4686-bc56-adae20031751
		summarizeBy: none
		sourceColumn: IsPending

		annotation SummarizationSetBy = Automatic

	column IsRightCensored
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 909de57a-9ce8-4769-b7fa-ee4b1f20d167
		summarizeBy: none
		sourceColumn: IsRightCensored

		annotation SummarizationSetBy = Automatic

	column FollowUpDays
		dataType: int64
		formatString: 0
		lineageTag: 81217824-563f-4abf-b7ec-9e2fd70b769f
		summarizeBy: sum
		sourceColumn: FollowUpDays

		annotation SummarizationSetBy = Automatic

	column ProcessingDateMissing
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 970e84f3-5190-4809-986a-e737a757dd13
		summarizeBy: none
		sourceColumn: ProcessingDateMissing

		annotation SummarizationSetBy = Automatic

	column ProcessingDateInvalid
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 066eee75-3c2f-4e2c-a541-6dfc8ea71889
		summarizeBy: none
		sourceColumn: ProcessingDateInvalid

		annotation SummarizationSetBy = Automatic

	column IsAfterObservationEnd
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 93cbe629-b894-45c6-bcd2-34e0577f8110
		summarizeBy: none
		sourceColumn: IsAfterObservationEnd

		annotation SummarizationSetBy = Automatic

	column YearMonth =
			
			DATE(
			    YEAR(permits_clean[applied_date]),
			    MONTH(permits_clean[applied_date]),
			    1
			)
		formatString: yyyy-mmm
		lineageTag: a22fec31-25ab-4fed-a8b3-e7d47ac9ab72
		summarizeBy: none

		variation Variation
			isDefault
			relationship: bef3119e-1a03-4ac5-841a-bfebc55d8241
			defaultHierarchy: LocalDateTable_0004d7fb-b820-4ec4-9443-ea04713a4ff5.'Date Hierarchy'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Season Sort' =
			
			VAR MonthNumber =
			    MONTH(permits_clean[applied_date])
			RETURN
			    SWITCH(
			        TRUE(),
			        MonthNumber IN {12, 1, 2}, 1,
			        MonthNumber IN {3, 4, 5}, 2,
			        MonthNumber IN {6, 7, 8}, 3,
			        MonthNumber IN {9, 10, 11}, 4,
			        BLANK()
			    )
		formatString: 0
		lineageTag: c1fda902-7dbe-4089-9262-b1869a262fc3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition permits_clean = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "permits_clean", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"point", type text}, {"permit_number", type text}, {"address", type text}, {"applicant", type text}, {"category", type text}, {"description", type text}, {"proposed_use_code", type text}, {"proposed_use_description", type text}, {"permitteddiscretionary", type text}, {"land_use_district", type text}, {"landusedistrictdescription", type text}, {"statuscurrent", type text}, {"applied_date", type datetime}, {"decision_date", type datetime}, {"releasedate", type datetime}, {"mustcommencedate", type datetime}, {"decision", type text}, {"decisionby", type text}, {"communitycode", type text}, {"community", type text}, {"ward", Int64.Type}, {"quadrant", type text}, {"latitude", type number}, {"longitude", type number}, {"locationcount", Int64.Type}, {"locationtypes", type text}, {"locationaddresses", type text}, {"locationsgeojson", type text}, {"locationswkt", type text}, {"canceledrefuseddate", type datetime}, {"raw_point", type text}, {"raw_permit_number", type text}, {"raw_address", type text}, {"raw_applicant", type text}, {"raw_category", type text}, {"raw_description", type text}, {"raw_proposed_use_code", type text}, {"raw_proposed_use_description", type text}, {"raw_permitteddiscretionary", type text}, {"raw_land_use_district", type text}, {"raw_landusedistrictdescription", type text}, {"raw_statuscurrent", type text}, {"raw_applied_date", type datetime}, {"raw_decision_date", type datetime}, {"raw_releasedate", type datetime}, {"raw_mustcommencedate", type datetime}, {"raw_decision", type text}, {"raw_decisionby", type text}, {"raw_communitycode", type text}, {"raw_community", type text}, {"raw_ward", Int64.Type}, {"raw_quadrant", type text}, {"raw_latitude", type number}, {"raw_longitude", type number}, {"raw_locationcount", Int64.Type}, {"raw_locationtypes", type text}, {"raw_locationaddresses", type text}, {"raw_locationsgeojson", type text}, {"raw_locationswkt", type text}, {"raw_canceledrefuseddate", type datetime}, {"applied_date_invalid", type logical}, {"decision_date_invalid", type logical}, {"latitude_invalid", type logical}, {"longitude_invalid", type logical}, {"ClassificationRule", type text}, {"ValidationStatus", type text}, {"IncludeResidential", type logical}, {"ResidentialType", type text}, {"RezoningRelevant", type logical}, {"ClassificationNeedsReview", type logical}, {"ClassificationMatchCount", Int64.Type}, {"ClassificationConflictCount", Int64.Type}, {"ClassificationMatchedRules", type text}, {"Period", type text}, {"DecisionPeriod", type text}, {"PeriodSortKey", Int64.Type}, {"PeriodDateMissing", type logical}, {"PeriodDateInvalid", type logical}, {"CrossesPeriodBoundary", type logical}, {"Season", type text}, {"SeasonStartDate", type datetime}, {"SeasonEndDate", type datetime}, {"SeasonLabel", type text}, {"SeasonSortKey", Int64.Type}, {"IsCompleteSeason", type logical}, {"IsPartialSeason", type logical}, {"ProcessingDays", Int64.Type}, {"HasValidProcessingDays", type logical}, {"HasNegativeProcessingDays", type logical}, {"IsPending", type logical}, {"IsRightCensored", type logical}, {"FollowUpDays", Int64.Type}, {"ProcessingDateMissing", type logical}, {"ProcessingDateInvalid", type logical}, {"IsAfterObservationEnd", type logical}}, "en-US")
				in
				  #"Changed column type"

