table permit_volume
	lineageTag: 0763faaf-5f84-4e90-b348-a27bdeed034c

	column Period
		dataType: string
		lineageTag: e6253a19-795f-4d37-910c-18d102dccfbd
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column PermitCount
		dataType: int64
		formatString: 0
		lineageTag: c3c5598c-2fd1-48e4-8fa3-1385322c30d8
		summarizeBy: sum
		sourceColumn: PermitCount

		annotation SummarizationSetBy = Automatic

	column AllPermitCount
		dataType: int64
		formatString: 0
		lineageTag: 58157867-0aca-4839-9dd4-14c166e822ea
		summarizeBy: sum
		sourceColumn: AllPermitCount

		annotation SummarizationSetBy = Automatic

	column ExcludedCount
		dataType: int64
		formatString: 0
		lineageTag: c6a4892e-375c-4010-baa7-33777809ae95
		summarizeBy: sum
		sourceColumn: ExcludedCount

		annotation SummarizationSetBy = Automatic

	column ResidentialShare
		dataType: double
		lineageTag: 450a3500-e1ff-4f6c-a5ab-de4502daae0d
		summarizeBy: sum
		sourceColumn: ResidentialShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthCount
		dataType: int64
		formatString: 0
		lineageTag: e6593bd7-9508-43d2-be73-9d378a49ec6d
		summarizeBy: sum
		sourceColumn: MonthCount

		annotation SummarizationSetBy = Automatic

	column MeanMonthlyCount
		dataType: double
		lineageTag: 8c8dd947-57cf-4dec-990d-80493f035c44
		summarizeBy: sum
		sourceColumn: MeanMonthlyCount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MedianMonthlyCount
		dataType: double
		lineageTag: 115481f9-8c4a-4a1b-b606-d9a64f946c9d
		summarizeBy: sum
		sourceColumn: MedianMonthlyCount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExposureDays
		dataType: int64
		formatString: 0
		lineageTag: 8db11299-5fe0-4c4b-8f35-2bd683d1d763
		summarizeBy: sum
		sourceColumn: ExposureDays

		annotation SummarizationSetBy = Automatic

	column WindowStart
		dataType: dateTime
		formatString: General Date
		lineageTag: f9cc9c3e-84b3-451a-84d4-29ae72d98f8e
		summarizeBy: none
		sourceColumn: WindowStart

		variation Variation
			isDefault
			relationship: 2a364cf6-40d6-48cf-abf8-3b05b32d3ce4
			defaultHierarchy: LocalDateTable_2f62f10e-6587-4ef1-84af-34ad544a7f96.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column WindowEnd
		dataType: dateTime
		formatString: General Date
		lineageTag: 67a352a9-6bda-44af-aa5c-35e498f0ac35
		summarizeBy: none
		sourceColumn: WindowEnd

		variation Variation
			isDefault
			relationship: b5d33a96-a45f-48b9-9cf0-ee338f92d499
			defaultHierarchy: LocalDateTable_b9245e03-0bce-40a4-8cef-015452c053f0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column WindowSource
		dataType: string
		lineageTag: 5c42cf16-67d9-4a6f-9fe0-8632a0af35c1
		summarizeBy: none
		sourceColumn: WindowSource

		annotation SummarizationSetBy = Automatic

	column BaselinePeriod
		dataType: string
		lineageTag: 4c60eee6-3788-4afc-aa60-1181447f904b
		summarizeBy: none
		sourceColumn: BaselinePeriod

		annotation SummarizationSetBy = Automatic

	column AbsoluteChange
		dataType: int64
		formatString: 0
		lineageTag: 8c9ef73d-4797-4957-becc-085cccc530e0
		summarizeBy: sum
		sourceColumn: AbsoluteChange

		annotation SummarizationSetBy = Automatic

	column PercentChange
		dataType: double
		lineageTag: 93edc5cb-2ede-4e90-810d-177741afb1b5
		summarizeBy: sum
		sourceColumn: PercentChange

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DP_Rate30
		dataType: double
		lineageTag: 3c0254bd-6b77-49f6-9a01-55623b6fe5d3
		summarizeBy: sum
		sourceColumn: DP_Rate30

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition permit_volume = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "permit_volume", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"PermitCount", Int64.Type}, {"AllPermitCount", Int64.Type}, {"ExcludedCount", Int64.Type}, {"ResidentialShare", type number}, {"MonthCount", Int64.Type}, {"MeanMonthlyCount", type number}, {"MedianMonthlyCount", type number}, {"ExposureDays", Int64.Type}, {"WindowStart", type datetime}, {"WindowEnd", type datetime}, {"WindowSource", type text}, {"BaselinePeriod", type text}, {"AbsoluteChange", Int64.Type}, {"PercentChange", type number}, {"DP_Rate30", type number}}, "en-US")
				in
				  #"Changed column type"

