table processing_period_totals
	lineageTag: 80619d4d-d4d3-4ece-8703-e6778540a5a4

	column Period
		dataType: string
		lineageTag: cff40f3c-3345-4c74-bd49-643e719e2e66
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column AllPermitCount
		dataType: int64
		formatString: 0
		lineageTag: 24b101b8-8761-4ff6-9472-fcd605a8c67a
		summarizeBy: sum
		sourceColumn: AllPermitCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 0c7e28b6-be05-4d47-b106-8fe65614ddde
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column ExcludedCount
		dataType: int64
		formatString: 0
		lineageTag: df9e5869-0548-44d1-a7df-06e7e044fdc3
		summarizeBy: sum
		sourceColumn: ExcludedCount

		annotation SummarizationSetBy = Automatic

	column TotalCount
		dataType: int64
		formatString: 0
		lineageTag: 614a7bec-bca2-40f7-87ad-c071398b07ec
		summarizeBy: sum
		sourceColumn: TotalCount

		annotation SummarizationSetBy = Automatic

	column ValidCount
		dataType: int64
		formatString: 0
		lineageTag: f9ab500d-50b2-4b70-961e-cacfc65eecac
		summarizeBy: sum
		sourceColumn: ValidCount

		annotation SummarizationSetBy = Automatic

	column InvalidCount
		dataType: int64
		formatString: 0
		lineageTag: 2b7ce098-90ac-4ac4-8602-d7b25485f239
		summarizeBy: sum
		sourceColumn: InvalidCount

		annotation SummarizationSetBy = Automatic

	column PendingCount
		dataType: int64
		formatString: 0
		lineageTag: e5343630-310f-444c-aafc-9c4f9e9ff494
		summarizeBy: sum
		sourceColumn: PendingCount

		annotation SummarizationSetBy = Automatic

	column RightCensoredCount
		dataType: int64
		formatString: 0
		lineageTag: d9586a18-094b-470f-bd99-db98483eb77e
		summarizeBy: sum
		sourceColumn: RightCensoredCount

		annotation SummarizationSetBy = Automatic

	column ValidShare
		dataType: double
		lineageTag: 370f2108-c1a4-477b-a1a8-df2702433629
		summarizeBy: sum
		sourceColumn: ValidShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NegativeCount
		dataType: int64
		formatString: 0
		lineageTag: e8e1e8e8-fb45-44b6-b03b-c2f405c7341c
		summarizeBy: sum
		sourceColumn: NegativeCount

		annotation SummarizationSetBy = Automatic

	column MissingDateCount
		dataType: int64
		formatString: 0
		lineageTag: b8aca467-9ad3-4f0a-bb21-cb87ef123e1b
		summarizeBy: sum
		sourceColumn: MissingDateCount

		annotation SummarizationSetBy = Automatic

	column InvalidDateCount
		dataType: int64
		formatString: 0
		lineageTag: b953dd82-7801-47cf-beae-ef45c535c00c
		summarizeBy: sum
		sourceColumn: InvalidDateCount

		annotation SummarizationSetBy = Automatic

	column AfterObservationEndCount
		dataType: int64
		formatString: 0
		lineageTag: 18f0df2e-9c7f-4c59-a9d6-956c2753e923
		summarizeBy: sum
		sourceColumn: AfterObservationEndCount

		annotation SummarizationSetBy = Automatic

	partition processing_period_totals = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "processing_period_totals", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"AllPermitCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"ExcludedCount", Int64.Type}, {"TotalCount", Int64.Type}, {"ValidCount", Int64.Type}, {"InvalidCount", Int64.Type}, {"PendingCount", Int64.Type}, {"RightCensoredCount", Int64.Type}, {"ValidShare", type number}, {"NegativeCount", Int64.Type}, {"MissingDateCount", Int64.Type}, {"InvalidDateCount", Int64.Type}, {"AfterObservationEndCount", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

