table processing_type_summary
	lineageTag: 5808b82f-d38b-48f0-a2ed-5a0f3bbaacb3

	column Period
		dataType: string
		lineageTag: f039d683-a44d-482e-85f5-b4c74427a03f
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column ResidentialType
		dataType: string
		lineageTag: c21c5f2c-970d-4379-b96a-59a8de926824
		summarizeBy: none
		sourceColumn: ResidentialType

		annotation SummarizationSetBy = Automatic

	column TotalCount
		dataType: int64
		formatString: 0
		lineageTag: 398eaa5f-f93f-49af-91ae-ce3032cafc77
		summarizeBy: sum
		sourceColumn: TotalCount

		annotation SummarizationSetBy = Automatic

	column ValidCount
		dataType: int64
		formatString: 0
		lineageTag: 5c9ce0df-f706-4cbd-8758-abf4536c6de7
		summarizeBy: none
		sourceColumn: ValidCount

		annotation SummarizationSetBy = User

	column InvalidCount
		dataType: int64
		formatString: 0
		lineageTag: 88b0d447-a019-4878-9f0d-9a2021d3b87c
		summarizeBy: sum
		sourceColumn: InvalidCount

		annotation SummarizationSetBy = Automatic

	column PendingCount
		dataType: int64
		formatString: 0
		lineageTag: 6b4108f6-6b99-4161-bffd-675347395100
		summarizeBy: sum
		sourceColumn: PendingCount

		annotation SummarizationSetBy = Automatic

	column RightCensoredCount
		dataType: int64
		formatString: 0
		lineageTag: 62991bed-af64-41b2-976d-b6e68f746999
		summarizeBy: sum
		sourceColumn: RightCensoredCount

		annotation SummarizationSetBy = Automatic

	column ValidShare
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f5ce831a-9959-49e4-8edb-8fb12671044d
		summarizeBy: none
		sourceColumn: ValidShare

		annotation SummarizationSetBy = User

	column NegativeCount
		dataType: int64
		formatString: 0
		lineageTag: 5b13f21d-e385-4e33-a721-98a5a22f887d
		summarizeBy: sum
		sourceColumn: NegativeCount

		annotation SummarizationSetBy = Automatic

	column MissingDateCount
		dataType: int64
		formatString: 0
		lineageTag: 8bf45979-f52f-47ae-ba15-1815889f69a1
		summarizeBy: sum
		sourceColumn: MissingDateCount

		annotation SummarizationSetBy = Automatic

	column InvalidDateCount
		dataType: int64
		formatString: 0
		lineageTag: 5a7414cc-6174-44d8-ab15-d2c85c1ac81d
		summarizeBy: sum
		sourceColumn: InvalidDateCount

		annotation SummarizationSetBy = Automatic

	column AfterObservationEndCount
		dataType: int64
		formatString: 0
		lineageTag: 9c6d4c9c-8ffc-405c-81ce-bd283fe50c9e
		summarizeBy: sum
		sourceColumn: AfterObservationEndCount

		annotation SummarizationSetBy = Automatic

	column MedianProcessingDays
		dataType: double
		lineageTag: 0e1abb04-b70c-468b-b55e-be13e7bb36e9
		summarizeBy: none
		sourceColumn: MedianProcessingDays

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MeanProcessingDays
		dataType: double
		lineageTag: e3184f79-2bae-41a6-8117-433fadb6315f
		summarizeBy: sum
		sourceColumn: MeanProcessingDays

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Q1ProcessingDays
		dataType: double
		lineageTag: 54e0d60f-d8a7-4039-86b2-3627aaf72421
		summarizeBy: none
		sourceColumn: Q1ProcessingDays

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Q3ProcessingDays
		dataType: double
		lineageTag: 12943298-466d-4582-9a2e-de63425f0043
		summarizeBy: none
		sourceColumn: Q3ProcessingDays

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IQRProcessingDays
		dataType: double
		lineageTag: c26cf4eb-648e-4af2-ac23-8aef59df5311
		summarizeBy: none
		sourceColumn: IQRProcessingDays

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition processing_type_summary = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "processing_type_summary", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"ResidentialType", type text}, {"TotalCount", Int64.Type}, {"ValidCount", Int64.Type}, {"InvalidCount", Int64.Type}, {"PendingCount", Int64.Type}, {"RightCensoredCount", Int64.Type}, {"ValidShare", type number}, {"NegativeCount", Int64.Type}, {"MissingDateCount", Int64.Type}, {"InvalidDateCount", Int64.Type}, {"AfterObservationEndCount", Int64.Type}, {"MedianProcessingDays", type number}, {"MeanProcessingDays", type number}, {"Q1ProcessingDays", type number}, {"Q3ProcessingDays", type number}, {"IQRProcessingDays", type number}}, "en-US")
				in
				  #"Changed column type"

