table reconciliation
	lineageTag: 161fb01f-dfc4-4671-89ca-a864a4a54b60

	column Scope
		dataType: string
		lineageTag: 019bc182-e7cd-4373-b7fa-0ea7a203d36e
		summarizeBy: none
		sourceColumn: Scope

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		lineageTag: db31e82b-0afa-40e9-a1b7-9f57c2c2d831
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	column Metric
		dataType: string
		lineageTag: 351acd75-cf51-4521-9830-dff63a4f6777
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	column PythonValue
		dataType: int64
		formatString: 0
		lineageTag: a5c010ed-732b-456f-8e66-dc01d2a5df1f
		summarizeBy: sum
		sourceColumn: PythonValue

		annotation SummarizationSetBy = Automatic

	partition reconciliation = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Albert Leung\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_workbook.xlsx"), null, true),
				    reconciliation_Sheet = Source{[Item="reconciliation",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(reconciliation_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Scope", type text}, {"Group", type text}, {"Metric", type text}, {"PythonValue", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

