table reconciliation
	lineageTag: fa5301b2-b50a-4121-b6e5-670d6a8eb8b2

	column Scope
		dataType: string
		lineageTag: 809662eb-9cb8-48ed-ac38-65c6c304354a
		summarizeBy: none
		sourceColumn: Scope

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		lineageTag: 718f4cea-c3a6-420d-a1e5-5d728b3db915
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	column Metric
		dataType: string
		lineageTag: 9c673777-904c-4822-9f0c-1ffbd6362d4b
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	column PythonValue
		dataType: int64
		formatString: 0
		lineageTag: 4f0b7971-57d6-43ba-90d7-42e5308097a2
		summarizeBy: sum
		sourceColumn: PythonValue

		annotation SummarizationSetBy = Automatic

	partition reconciliation = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "reconciliation", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Scope", type text}, {"Group", type text}, {"Metric", type text}, {"PythonValue", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

