table rezoning_by_type
	lineageTag: 836510db-097b-4967-856c-ec8ce323dc1e

	column Period
		dataType: string
		lineageTag: 5dc76c0f-35e8-4b2d-8a2e-c38b333bf30b
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column ResidentialType
		dataType: string
		lineageTag: 52e7f445-6874-4f71-9c23-7745e1bf98c9
		summarizeBy: none
		sourceColumn: ResidentialType

		annotation SummarizationSetBy = Automatic

	column GroupResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: fd369549-c90b-409d-a788-449d6942fd6a
		summarizeBy: sum
		sourceColumn: GroupResidentialCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 0b0b9d1e-0f5c-4aed-862c-9e30958faa55
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column RezoningRelevantCount
		dataType: int64
		formatString: 0
		lineageTag: 9805a2bd-f508-4499-957e-9751e2a6fee8
		summarizeBy: sum
		sourceColumn: RezoningRelevantCount

		annotation SummarizationSetBy = Automatic

	column NotRezoningRelevantCount
		dataType: int64
		formatString: 0
		lineageTag: 3a0cd32d-f169-41c4-8a0e-990a254c0b31
		summarizeBy: sum
		sourceColumn: NotRezoningRelevantCount

		annotation SummarizationSetBy = Automatic

	column UnknownRelevanceCount
		dataType: int64
		formatString: 0
		lineageTag: 44e831ed-6c91-4ef3-96cf-1fef8224734c
		summarizeBy: sum
		sourceColumn: UnknownRelevanceCount

		annotation SummarizationSetBy = Automatic

	column RezoningRelevantShare
		dataType: double
		lineageTag: c31610ca-e56a-4dd9-8223-571928848b17
		summarizeBy: sum
		sourceColumn: RezoningRelevantShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NotRezoningRelevantShare
		dataType: double
		lineageTag: f1feab71-0240-4ee1-a7b8-b1222fd5f778
		summarizeBy: sum
		sourceColumn: NotRezoningRelevantShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnknownRelevanceShare
		dataType: int64
		formatString: 0
		lineageTag: f4039415-ecce-4d70-9aca-ad48a2468c03
		summarizeBy: sum
		sourceColumn: UnknownRelevanceShare

		annotation SummarizationSetBy = Automatic

	column ReviewCount
		dataType: int64
		formatString: 0
		lineageTag: ffe300e2-d71e-404c-8ae6-aa7669f2d5bc
		summarizeBy: sum
		sourceColumn: ReviewCount

		annotation SummarizationSetBy = Automatic

	partition rezoning_by_type = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Albert Leung\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_workbook.xlsx"), null, true),
				    rezoning_by_type_Sheet = Source{[Item="rezoning_by_type",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(rezoning_by_type_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Period", type text}, {"ResidentialType", type text}, {"GroupResidentialCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"RezoningRelevantCount", Int64.Type}, {"NotRezoningRelevantCount", Int64.Type}, {"UnknownRelevanceCount", Int64.Type}, {"RezoningRelevantShare", type number}, {"NotRezoningRelevantShare", type number}, {"UnknownRelevanceShare", Int64.Type}, {"ReviewCount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

