table rezoning_by_district
	lineageTag: d052b558-0d1a-4f14-b0ef-f453e41cc219

	column Period
		dataType: string
		lineageTag: 2f9ba857-a4e7-4b75-b1f7-8cc8ff3ce9be
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column land_use_district
		dataType: string
		lineageTag: 01195561-1899-413e-8f3b-ca651c80cd4e
		summarizeBy: none
		sourceColumn: land_use_district

		annotation SummarizationSetBy = Automatic

	column GroupResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 849b0e02-f96f-4523-926c-cc0fc301a71e
		summarizeBy: sum
		sourceColumn: GroupResidentialCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 12356f0b-5823-4d1d-9858-12d01f37d4bc
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column RezoningRelevantCount
		dataType: int64
		formatString: 0
		lineageTag: 47613477-9697-43dd-aa40-918e42913898
		summarizeBy: sum
		sourceColumn: RezoningRelevantCount

		annotation SummarizationSetBy = Automatic

	column NotRezoningRelevantCount
		dataType: int64
		formatString: 0
		lineageTag: 2b73bfd2-aede-4e40-a0ea-738b6a3b2eca
		summarizeBy: sum
		sourceColumn: NotRezoningRelevantCount

		annotation SummarizationSetBy = Automatic

	column UnknownRelevanceCount
		dataType: int64
		formatString: 0
		lineageTag: b049e5c9-c3b4-4b75-a500-217f3731265d
		summarizeBy: sum
		sourceColumn: UnknownRelevanceCount

		annotation SummarizationSetBy = Automatic

	column RezoningRelevantShare
		dataType: double
		lineageTag: 9a22d665-20d0-4c7b-bdf6-75a1b2cd3bda
		summarizeBy: sum
		sourceColumn: RezoningRelevantShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NotRezoningRelevantShare
		dataType: double
		lineageTag: 4611dd70-6e23-4f52-9f08-97714792b74d
		summarizeBy: sum
		sourceColumn: NotRezoningRelevantShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnknownRelevanceShare
		dataType: int64
		formatString: 0
		lineageTag: daba3189-ce35-42b4-bf30-c01e57d63151
		summarizeBy: sum
		sourceColumn: UnknownRelevanceShare

		annotation SummarizationSetBy = Automatic

	column ReviewCount
		dataType: int64
		formatString: 0
		lineageTag: df72d9d6-cb06-4aeb-9257-3ab215f3726c
		summarizeBy: sum
		sourceColumn: ReviewCount

		annotation SummarizationSetBy = Automatic

	partition rezoning_by_district = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Albert Leung\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_workbook.xlsx"), null, true),
				    rezoning_by_district_Sheet = Source{[Item="rezoning_by_district",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(rezoning_by_district_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Period", type text}, {"land_use_district", type text}, {"GroupResidentialCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"RezoningRelevantCount", Int64.Type}, {"NotRezoningRelevantCount", Int64.Type}, {"UnknownRelevanceCount", Int64.Type}, {"RezoningRelevantShare", type number}, {"NotRezoningRelevantShare", type number}, {"UnknownRelevanceShare", Int64.Type}, {"ReviewCount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

