table rezoning_summary
	lineageTag: f85bf2a8-c92a-4588-9f83-aab3d568ace8

	column Period
		dataType: string
		lineageTag: 01734a0f-3108-45fa-9819-c1302ad6f465
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column AllPermitCount
		dataType: int64
		formatString: 0
		lineageTag: f88ef17d-4870-4bd1-9048-23e329665b8c
		summarizeBy: sum
		sourceColumn: AllPermitCount

		annotation SummarizationSetBy = Automatic

	column ExcludedCount
		dataType: int64
		formatString: 0
		lineageTag: 435329eb-4216-47bd-9b6e-8e78b7783da1
		summarizeBy: sum
		sourceColumn: ExcludedCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 9234f99b-d1e1-4343-b752-d17e517ee027
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column RezoningRelevantCount
		dataType: int64
		formatString: 0
		lineageTag: 81874456-35ab-4bab-b0d2-18838cf3cafa
		summarizeBy: sum
		sourceColumn: RezoningRelevantCount

		annotation SummarizationSetBy = Automatic

	column NotRezoningRelevantCount
		dataType: int64
		formatString: 0
		lineageTag: be4a5f3c-f768-4ca7-93bb-daf98c048737
		summarizeBy: sum
		sourceColumn: NotRezoningRelevantCount

		annotation SummarizationSetBy = Automatic

	column UnknownRelevanceCount
		dataType: int64
		formatString: 0
		lineageTag: d61de698-341b-4634-948c-be4e285d5324
		summarizeBy: sum
		sourceColumn: UnknownRelevanceCount

		annotation SummarizationSetBy = Automatic

	column RezoningRelevantShare
		dataType: double
		lineageTag: 08a2a6d2-e32f-4bed-b887-e182eb248f60
		summarizeBy: sum
		sourceColumn: RezoningRelevantShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NotRezoningRelevantShare
		dataType: double
		lineageTag: 782d7d31-b507-4766-997b-5bd62e6c2024
		summarizeBy: sum
		sourceColumn: NotRezoningRelevantShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnknownRelevanceShare
		dataType: int64
		formatString: 0
		lineageTag: f1f6c32a-bb89-48bd-b5b5-0a2d7069ac89
		summarizeBy: sum
		sourceColumn: UnknownRelevanceShare

		annotation SummarizationSetBy = Automatic

	column ReviewCount
		dataType: int64
		formatString: 0
		lineageTag: b0eb3eb5-40bf-4198-98fb-bb4df34a2bd0
		summarizeBy: sum
		sourceColumn: ReviewCount

		annotation SummarizationSetBy = Automatic

	partition rezoning_summary = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "rezoning_summary", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"AllPermitCount", Int64.Type}, {"ExcludedCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"RezoningRelevantCount", Int64.Type}, {"NotRezoningRelevantCount", Int64.Type}, {"UnknownRelevanceCount", Int64.Type}, {"RezoningRelevantShare", type number}, {"NotRezoningRelevantShare", type number}, {"UnknownRelevanceShare", Int64.Type}, {"ReviewCount", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

