table rezoning_by_district
	lineageTag: 175d1e84-ebea-46e4-91e2-76afadfb262d

	column Period
		dataType: string
		lineageTag: 306c273e-f3e5-4e64-ade3-7f9483bab4ec
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column land_use_district
		dataType: string
		lineageTag: b0d30968-a6f5-4406-b2ee-fe222355a205
		summarizeBy: none
		sourceColumn: land_use_district

		annotation SummarizationSetBy = Automatic

	column GroupResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 0e925e52-b390-479f-85fc-34f27a65bd9c
		summarizeBy: sum
		sourceColumn: GroupResidentialCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 4c4f09a6-bb9f-4cbb-bd04-96621b122d34
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column RezoningRelevantCount
		dataType: int64
		formatString: 0
		lineageTag: 589a7b92-ac03-45cc-ab14-853867b7f073
		summarizeBy: sum
		sourceColumn: RezoningRelevantCount

		annotation SummarizationSetBy = Automatic

	column NotRezoningRelevantCount
		dataType: int64
		formatString: 0
		lineageTag: d1b6d3bb-fa3d-4d19-8907-1136401fbd0c
		summarizeBy: sum
		sourceColumn: NotRezoningRelevantCount

		annotation SummarizationSetBy = Automatic

	column UnknownRelevanceCount
		dataType: int64
		formatString: 0
		lineageTag: e2d920a4-c1e3-4c85-a23d-e7676fd47328
		summarizeBy: sum
		sourceColumn: UnknownRelevanceCount

		annotation SummarizationSetBy = Automatic

	column RezoningRelevantShare
		dataType: double
		lineageTag: c1ee4473-729c-4fa0-899d-24b0e507ecc3
		summarizeBy: sum
		sourceColumn: RezoningRelevantShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NotRezoningRelevantShare
		dataType: double
		lineageTag: 9cb4e200-8908-4501-bfef-6eeb8644dbf7
		summarizeBy: sum
		sourceColumn: NotRezoningRelevantShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnknownRelevanceShare
		dataType: int64
		formatString: 0
		lineageTag: 3ec5f63d-71ba-4598-8ee2-254ccf86bfa6
		summarizeBy: sum
		sourceColumn: UnknownRelevanceShare

		annotation SummarizationSetBy = Automatic

	column ReviewCount
		dataType: int64
		formatString: 0
		lineageTag: 989db584-0115-4041-838b-6f39469b51fb
		summarizeBy: sum
		sourceColumn: ReviewCount

		annotation SummarizationSetBy = Automatic

	partition rezoning_by_district = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "rezoning_by_district", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"land_use_district", type text}, {"GroupResidentialCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"RezoningRelevantCount", Int64.Type}, {"NotRezoningRelevantCount", Int64.Type}, {"UnknownRelevanceCount", Int64.Type}, {"RezoningRelevantShare", type number}, {"NotRezoningRelevantShare", type number}, {"UnknownRelevanceShare", Int64.Type}, {"ReviewCount", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

