table seasonal_monthly_volume
	lineageTag: fc5ae154-6d63-47ed-a405-c0c30de0e64c

	column Period
		dataType: string
		lineageTag: 847dda79-04b2-4d29-b83b-3db2b7ab2b3c
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: 471709c9-477c-4892-95af-ec49f1ebec5e
		summarizeBy: none
		sourceColumn: YearMonth

		variation Variation
			isDefault
			relationship: e3815dd1-0aa5-443d-9ea8-6e0da1c09d53
			defaultHierarchy: LocalDateTable_86df7c65-5ad1-4b0a-9e69-179a548c435d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column PermitCount
		dataType: int64
		formatString: 0
		lineageTag: 0389123e-9d91-4209-b23c-924408e83cba
		summarizeBy: sum
		sourceColumn: PermitCount

		annotation SummarizationSetBy = Automatic

	column AllPermitCount
		dataType: int64
		formatString: 0
		lineageTag: 0b256201-63d4-4e81-8796-9ea05eb460fa
		summarizeBy: sum
		sourceColumn: AllPermitCount

		annotation SummarizationSetBy = Automatic

	column ExcludedCount
		dataType: int64
		formatString: 0
		lineageTag: e49caa2f-0bc8-443f-9944-0c7eae5b763e
		summarizeBy: sum
		sourceColumn: ExcludedCount

		annotation SummarizationSetBy = Automatic

	column ResidentialShare
		dataType: double
		lineageTag: cdd89fa7-a39b-4675-a3dc-93fa9dd4ede4
		summarizeBy: sum
		sourceColumn: ResidentialShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExposureDays
		dataType: int64
		formatString: 0
		lineageTag: ddeeb25a-ede0-4fbc-a813-d0c65b64d458
		summarizeBy: sum
		sourceColumn: ExposureDays

		annotation SummarizationSetBy = Automatic

	column IsPartialMonth
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c9d95105-eb4d-4e19-b3f1-bde31c45aa93
		summarizeBy: none
		sourceColumn: IsPartialMonth

		annotation SummarizationSetBy = Automatic

	column WindowSource
		dataType: string
		lineageTag: e810f86d-edd9-4a82-8816-17383c8acab8
		summarizeBy: none
		sourceColumn: WindowSource

		annotation SummarizationSetBy = Automatic

	column DP_Rate30
		dataType: double
		lineageTag: e97a038a-7057-4b82-9d76-4eb5bcbd5f31
		summarizeBy: sum
		sourceColumn: DP_Rate30

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition seasonal_monthly_volume = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "seasonal_monthly_volume", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"YearMonth", type datetime}, {"PermitCount", Int64.Type}, {"AllPermitCount", Int64.Type}, {"ExcludedCount", Int64.Type}, {"ResidentialShare", type number}, {"ExposureDays", Int64.Type}, {"IsPartialMonth", type logical}, {"WindowSource", type text}, {"DP_Rate30", type number}}, "en-US")
				in
				  #"Changed column type"

