table sensitivity_summary
	lineageTag: c0cf624e-9b10-4914-a815-a61c2dadd52e

	column Column1
		dataType: string
		lineageTag: 0e13c627-f9bb-40cd-825f-bf2a790f7fc2
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 4addf261-c209-4ce1-9225-4649a1b1d578
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 599b9fa5-11f8-4fcf-86c1-3a89dc874f85
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: bca01656-1766-40b4-a28d-c3dd9f9a73f3
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 565f679d-c3a6-4b6d-9caa-0554da3d3ee2
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 590c40b5-03a8-4847-ad93-d706717f87fc
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 32041244-7329-4f1c-b9dd-d72c61d1bf06
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: d0e6d7ed-7455-4052-a19d-308f5c9cc9da
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	partition sensitivity_summary = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "sensitivity_summary", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}}, "en-US")
				in
				  #"Changed column type"

