table type_summary
	lineageTag: 55c9e18b-712d-4c5a-b44c-196c7eaaa10a

	column Period
		dataType: string
		lineageTag: adc44c02-f0e4-4a22-b053-198c8bd8899f
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column ResidentialType
		dataType: string
		lineageTag: 0656950a-5fcb-4d79-bc49-cac6be247549
		summarizeBy: none
		sourceColumn: ResidentialType

		annotation SummarizationSetBy = Automatic

	column PermitCount
		dataType: int64
		formatString: 0
		lineageTag: 608db901-7773-49aa-b62d-64b804d673b0
		summarizeBy: sum
		sourceColumn: PermitCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: efa4ef60-af61-44fa-a3a4-bddcb70eb8bb
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column TypeShare
		dataType: double
		lineageTag: 8f45c902-46f9-4607-a82b-0767f17a9bab
		summarizeBy: sum
		sourceColumn: TypeShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BaselinePeriod
		dataType: string
		lineageTag: 810f7305-a416-46f5-8cd1-a7c106e50d0a
		summarizeBy: none
		sourceColumn: BaselinePeriod

		annotation SummarizationSetBy = Automatic

	column BaselinePermitCount
		dataType: int64
		formatString: 0
		lineageTag: 2ec6c9fd-24f2-4e76-a4dc-3adf28aa2358
		summarizeBy: sum
		sourceColumn: BaselinePermitCount

		annotation SummarizationSetBy = Automatic

	column AbsoluteChange
		dataType: int64
		formatString: 0
		lineageTag: eda1769d-cd3f-42bc-8f20-728de7c55860
		summarizeBy: sum
		sourceColumn: AbsoluteChange

		annotation SummarizationSetBy = Automatic

	column PercentChange
		dataType: double
		lineageTag: 8adb789b-3712-4179-9b8c-9fdf78fff9b1
		summarizeBy: sum
		sourceColumn: PercentChange

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShareChangePercentagePoints
		dataType: double
		lineageTag: 573125a0-47b4-4acd-831e-b89000095da7
		summarizeBy: sum
		sourceColumn: ShareChangePercentagePoints

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition type_summary = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "type_summary", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"ResidentialType", type text}, {"PermitCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"TypeShare", type number}, {"BaselinePeriod", type text}, {"BaselinePermitCount", Int64.Type}, {"AbsoluteChange", Int64.Type}, {"PercentChange", type number}, {"ShareChangePercentagePoints", type number}}, "en-US")
				in
				  #"Changed column type"

