table type_summary
	lineageTag: 25ca8898-faf5-4a47-9238-519e4fffdfb7

	column Period
		dataType: string
		lineageTag: a9efddc9-6421-4b6a-b20a-3181c1c2bc1d
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column ResidentialType
		dataType: string
		lineageTag: e94483b2-e2da-4e39-a8bb-451590ad63bf
		summarizeBy: none
		sourceColumn: ResidentialType

		annotation SummarizationSetBy = Automatic

	column PermitCount
		dataType: int64
		formatString: 0
		lineageTag: 12bfcad1-1c36-4692-b946-235241b3aaba
		summarizeBy: sum
		sourceColumn: PermitCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 3aa98e5a-89f8-4e5a-94eb-fa839c9f1c61
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column TypeShare
		dataType: double
		lineageTag: 04b8a973-32a3-41ac-9e29-eaa83da706e6
		summarizeBy: sum
		sourceColumn: TypeShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BaselinePeriod
		dataType: string
		lineageTag: e714ec89-928b-4427-b690-817c26a505f3
		summarizeBy: none
		sourceColumn: BaselinePeriod

		annotation SummarizationSetBy = Automatic

	column BaselinePermitCount
		dataType: int64
		formatString: 0
		lineageTag: 4d7dde72-96c9-4ff3-bf0b-e98a0e78c8fc
		summarizeBy: sum
		sourceColumn: BaselinePermitCount

		annotation SummarizationSetBy = Automatic

	column AbsoluteChange
		dataType: int64
		formatString: 0
		lineageTag: 6088f5e4-5e08-4183-b238-4f816d5b360e
		summarizeBy: sum
		sourceColumn: AbsoluteChange

		annotation SummarizationSetBy = Automatic

	column PercentChange
		dataType: double
		lineageTag: a7b8dfe0-8fa0-4d63-8718-7e3a4fc6d865
		summarizeBy: sum
		sourceColumn: PercentChange

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShareChangePercentagePoints
		dataType: double
		lineageTag: 7638b147-cd79-4efd-aa6c-64919f2b5188
		summarizeBy: sum
		sourceColumn: ShareChangePercentagePoints

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition type_summary = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Albert Leung\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_workbook.xlsx"), null, true),
				    type_summary_Sheet = Source{[Item="type_summary",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(type_summary_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Period", type text}, {"ResidentialType", type text}, {"PermitCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"TypeShare", type number}, {"BaselinePeriod", type text}, {"BaselinePermitCount", Int64.Type}, {"AbsoluteChange", Int64.Type}, {"PercentChange", type number}, {"ShareChangePercentagePoints", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

