table type_period_totals
	lineageTag: 0ffeaebe-7da7-47ab-a9cb-cc04aa42b2eb

	column Period
		dataType: string
		lineageTag: 6bc3d6f1-ddc8-44d1-bc35-a5558c14d9a7
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column AllPermitCount
		dataType: int64
		formatString: 0
		lineageTag: bf8e96e3-7c67-4f52-9e23-d3ce6f8781a8
		summarizeBy: sum
		sourceColumn: AllPermitCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 1144eef9-de6b-444a-9c13-61e9c408bef0
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column ExcludedCount
		dataType: int64
		formatString: 0
		lineageTag: 9fef8f9f-6b0f-48d0-ac85-3dd2575d91f2
		summarizeBy: sum
		sourceColumn: ExcludedCount

		annotation SummarizationSetBy = Automatic

	partition type_period_totals = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Albert Leung\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_workbook.xlsx"), null, true),
				    type_period_totals_Sheet = Source{[Item="type_period_totals",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(type_period_totals_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Period", type text}, {"AllPermitCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"ExcludedCount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

