table unknown_seasons
	lineageTag: b795defe-cb46-4c28-86f8-bd58147ff750

	column Column1
		dataType: string
		lineageTag: 6826f51c-296f-421e-b3c1-4af017e29999
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: e815a015-4346-4c9d-8049-5edb9cbd28b5
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 3da5516b-7886-4097-af81-539fc8bc0cd3
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 341811e7-f1f6-49e0-8cfd-115723a61d5d
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 919dbbf1-24aa-4a10-870c-cb2f0bb94d74
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 2316e9cf-ba7f-4367-a9dd-2767e4d790cb
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 964088fa-2dff-4512-8062-ddf7757657bd
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: f87e45f2-1559-45e6-acb8-40dbe475566b
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: c18ff2aa-91cc-4614-ac54-e1bf8b5694fa
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: 5828594c-0a2d-4106-b914-e9d86ba27177
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: fc1560e4-e0cf-4ae5-9b51-075cbb46cb5b
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 78232877-6457-4711-bf95-8d2bb1270f42
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 2ef75e49-9ad6-4b91-a2c6-ba8f02f0e38d
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: 6aef8dfc-674e-40f0-ad92-873085a9e1b4
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 64e8b4d0-95ca-4aaa-b6c9-7ce29a44297c
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: 5c08a96f-c734-41bc-8184-c9880b462917
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: 606f1f4b-9ab1-4bc8-99a8-efc841aa688c
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 35600f22-273a-4a29-b83b-791864548e24
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		lineageTag: 70c56fb4-10e1-4824-a665-bc915e90167e
		summarizeBy: none
		sourceColumn: Column19

		annotation SummarizationSetBy = Automatic

	column Column20
		dataType: string
		lineageTag: 53388616-0cf4-47b1-be3f-59f98f6da547
		summarizeBy: none
		sourceColumn: Column20

		annotation SummarizationSetBy = Automatic

	column Column21
		dataType: string
		lineageTag: 82ad759e-94ce-468f-9df8-adf4ad56b515
		summarizeBy: none
		sourceColumn: Column21

		annotation SummarizationSetBy = Automatic

	column Column22
		dataType: string
		lineageTag: ec88a1f1-9a28-44f4-9bff-7d9e01ddd093
		summarizeBy: none
		sourceColumn: Column22

		annotation SummarizationSetBy = Automatic

	column Column23
		dataType: string
		lineageTag: 3bbfef90-e3e3-42bd-baf0-5ad49b482a38
		summarizeBy: none
		sourceColumn: Column23

		annotation SummarizationSetBy = Automatic

	column Column24
		dataType: string
		lineageTag: 1906caa2-9199-4dd5-ae38-017f97c329df
		summarizeBy: none
		sourceColumn: Column24

		annotation SummarizationSetBy = Automatic

	column Column25
		dataType: string
		lineageTag: 3b106e62-dabe-426a-9513-6ae709fb4246
		summarizeBy: none
		sourceColumn: Column25

		annotation SummarizationSetBy = Automatic

	column Column26
		dataType: string
		lineageTag: bb84cff5-8abb-4177-b087-ef25fc8c019d
		summarizeBy: none
		sourceColumn: Column26

		annotation SummarizationSetBy = Automatic

	partition unknown_seasons = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "unknown_seasons", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}}, "en-US")
				in
				  #"Changed column type"

