table validation_data_quality_validat
	lineageTag: 14a3ef41-5a7f-489f-bbbf-8efa9d8439d3

	column check_name
		dataType: string
		lineageTag: c3ecc528-e199-4195-8ac1-89489837ea6b
		summarizeBy: none
		sourceColumn: check_name

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: a1573a95-ca2f-44e3-bb29-af77b1d08f16
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column affected_rows
		dataType: int64
		formatString: 0
		lineageTag: 25858c41-53b1-454c-8ccb-681bb4683248
		summarizeBy: sum
		sourceColumn: affected_rows

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		lineageTag: 57d3c117-64d6-44b4-80e3-22613660c811
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	partition validation_data_quality_validat = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "validation_data_quality_validat", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"check_name", type text}, {"status", type text}, {"affected_rows", Int64.Type}, {"message", type text}}, "en-US")
				in
				  #"Changed column type"

