table validation_data_quality_validat
	lineageTag: 91059bae-ebb4-4fb2-9d23-65959b3115b1

	column check_name
		dataType: string
		lineageTag: c171d0a8-3076-4ea0-99b8-63e9c312fe5a
		summarizeBy: none
		sourceColumn: check_name

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 574adb07-335c-441f-a3ae-84735188d8c7
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column affected_rows
		dataType: int64
		formatString: 0
		lineageTag: d0247688-0cc2-4e71-8dce-3d14577e941d
		summarizeBy: sum
		sourceColumn: affected_rows

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		lineageTag: affcf576-b5e0-4f11-8e01-3189c8c4b608
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	partition validation_data_quality_validat = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Albert Leung\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_workbook.xlsx"), null, true),
				    validation_data_quality_validat_Sheet = Source{[Item="validation_data_quality_validat",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(validation_data_quality_validat_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"check_name", type text}, {"status", type text}, {"affected_rows", Int64.Type}, {"message", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

