table validation_classification_valid
	lineageTag: 77250161-5605-4254-857a-77641203f2e6

	column report_type
		dataType: string
		lineageTag: 22efc875-3bc6-4513-8032-28e0bc078dc2
		summarizeBy: none
		sourceColumn: report_type

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 39baca6a-f6d2-4826-9c96-fa8f1e5fc0aa
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column record_count
		dataType: int64
		formatString: 0
		lineageTag: 95fefc9f-2ecb-4d92-b3d6-0c3a657f2667
		summarizeBy: sum
		sourceColumn: record_count

		annotation SummarizationSetBy = Automatic

	column matched_count
		dataType: int64
		formatString: 0
		lineageTag: 86e40787-3d19-4713-8979-4f22ff52fb33
		summarizeBy: sum
		sourceColumn: matched_count

		annotation SummarizationSetBy = Automatic

	column unmatched_count
		dataType: int64
		formatString: 0
		lineageTag: 94404f90-6bbb-4614-91b6-313ba7071b24
		summarizeBy: sum
		sourceColumn: unmatched_count

		annotation SummarizationSetBy = Automatic

	column coverage_percentage
		dataType: double
		lineageTag: d5b21706-e36f-4e5a-a5f5-c7edc470e122
		summarizeBy: sum
		sourceColumn: coverage_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unmatched_percentage
		dataType: double
		lineageTag: 534406c4-7088-4cb4-ab7e-bb45558c11ef
		summarizeBy: sum
		sourceColumn: unmatched_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column review_count
		dataType: int64
		formatString: 0
		lineageTag: f5102053-9b86-4e11-8aaa-cfc21cb19cc4
		summarizeBy: sum
		sourceColumn: review_count

		annotation SummarizationSetBy = Automatic

	column review_percentage
		dataType: double
		lineageTag: b106e7b0-40b3-4592-b196-7e3a95f7beb4
		summarizeBy: sum
		sourceColumn: review_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column overlap_count
		dataType: int64
		formatString: 0
		lineageTag: d882b2dd-dcb0-4bf4-9bd0-f498eb7db699
		summarizeBy: sum
		sourceColumn: overlap_count

		annotation SummarizationSetBy = Automatic

	column additional_match_count
		dataType: int64
		formatString: 0
		lineageTag: 07598b80-9a42-485f-90f9-d79b763a5afe
		summarizeBy: sum
		sourceColumn: additional_match_count

		annotation SummarizationSetBy = Automatic

	column unknown_rule_count
		dataType: int64
		formatString: 0
		lineageTag: e21e0735-e131-4a9e-8c49-097fd7891fe0
		summarizeBy: sum
		sourceColumn: unknown_rule_count

		annotation SummarizationSetBy = Automatic

	column disabled_rule_count
		dataType: int64
		formatString: 0
		lineageTag: 74c21930-f9a3-482d-b1fa-66f41099d47c
		summarizeBy: sum
		sourceColumn: disabled_rule_count

		annotation SummarizationSetBy = Automatic

	column inconsistent_audit_count
		dataType: int64
		formatString: 0
		lineageTag: 4c781ce3-514a-4c28-8f2d-00b7152821bd
		summarizeBy: sum
		sourceColumn: inconsistent_audit_count

		annotation SummarizationSetBy = Automatic

	column missing_audit_columns
		dataType: string
		lineageTag: 9f574b2a-5945-46aa-bcc1-4ba3f48d75db
		summarizeBy: none
		sourceColumn: missing_audit_columns

		annotation SummarizationSetBy = Automatic

	column enabled_rule_count
		dataType: int64
		formatString: 0
		lineageTag: 2688eb14-afba-43c7-95d5-8e125a4c494d
		summarizeBy: sum
		sourceColumn: enabled_rule_count

		annotation SummarizationSetBy = Automatic

	column audit_count
		dataType: string
		lineageTag: ecf79e0d-a096-4059-ad7c-f1aa20b2d9b7
		summarizeBy: none
		sourceColumn: audit_count

		annotation SummarizationSetBy = Automatic

	column audit_error_count
		dataType: string
		lineageTag: ce20da62-9ae2-4a24-a983-1f260fdd1bdb
		summarizeBy: none
		sourceColumn: audit_error_count

		annotation SummarizationSetBy = Automatic

	column audit_accuracy_percentage
		dataType: string
		lineageTag: 382bfcb4-3d23-4d33-bb8a-611d0486ec33
		summarizeBy: none
		sourceColumn: audit_accuracy_percentage

		annotation SummarizationSetBy = Automatic

	column expected_type
		dataType: string
		lineageTag: 3218593e-7f69-4f85-8320-44924113c3fa
		summarizeBy: none
		sourceColumn: expected_type

		annotation SummarizationSetBy = Automatic

	column predicted_type
		dataType: string
		lineageTag: e5d2f5e3-a32d-4bd8-a8a0-c9011dae3c73
		summarizeBy: none
		sourceColumn: predicted_type

		annotation SummarizationSetBy = Automatic

	column review_status_count
		dataType: int64
		formatString: 0
		lineageTag: 1f0a6af2-0fa5-4fa2-b62e-736fd48e4c30
		summarizeBy: sum
		sourceColumn: review_status_count

		annotation SummarizationSetBy = Automatic

	column provisional_status_count
		dataType: int64
		formatString: 0
		lineageTag: f2f539aa-7da4-40b7-abd6-744cebbdb874
		summarizeBy: sum
		sourceColumn: provisional_status_count

		annotation SummarizationSetBy = Automatic

	column fallback_status_count
		dataType: int64
		formatString: 0
		lineageTag: f1cf8b75-a146-4cd2-8c89-8f05b5da7709
		summarizeBy: sum
		sourceColumn: fallback_status_count

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		lineageTag: c1c43d7d-b702-4c39-a1cb-f644ef892be5
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	partition validation_classification_valid = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "validation_classification_valid", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"report_type", type text}, {"status", type text}, {"record_count", Int64.Type}, {"matched_count", Int64.Type}, {"unmatched_count", Int64.Type}, {"coverage_percentage", type number}, {"unmatched_percentage", type number}, {"review_count", Int64.Type}, {"review_percentage", type number}, {"overlap_count", Int64.Type}, {"additional_match_count", Int64.Type}, {"unknown_rule_count", Int64.Type}, {"disabled_rule_count", Int64.Type}, {"inconsistent_audit_count", Int64.Type}, {"enabled_rule_count", Int64.Type}, {"review_status_count", Int64.Type}, {"provisional_status_count", Int64.Type}, {"fallback_status_count", Int64.Type}, {"message", type text}}, "en-US")
				in
				  #"Changed column type"

