table validation_schema_validator
	lineageTag: 65711379-37ed-420b-ad69-e6006ff7f0dd

	column Column1
		dataType: string
		lineageTag: af2aba69-19ef-41af-b051-61fc8961a057
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: ce3a4f6d-da91-4f8d-a322-35e12abf1e54
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: c2d3e9b6-ce0d-4f44-92b0-834e340d0985
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	partition validation_schema_validator = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "validation_schema_validator", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}, "en-US")
				in
				  #"Changed column type"

