table ward_summary
	lineageTag: 761796d5-2a52-49ff-83c9-2d1449826e8c

	column Period
		dataType: string
		lineageTag: dd234833-8f6b-4861-854c-baaf6453765c
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column Ward
		dataType: int64
		formatString: 0
		lineageTag: 5011be47-6820-42de-a687-dfc73760cb43
		summarizeBy: sum
		sourceColumn: Ward

		annotation SummarizationSetBy = Automatic

	column IsMissingGeography
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e7ef964c-7315-453c-9240-09ab2788b5c4
		summarizeBy: none
		sourceColumn: IsMissingGeography

		annotation SummarizationSetBy = Automatic

	column PermitCount
		dataType: int64
		formatString: 0
		lineageTag: 2d5d0f86-5bb3-45c5-8ccf-f76f3a7a7445
		summarizeBy: sum
		sourceColumn: PermitCount

		annotation SummarizationSetBy = Automatic

	column PeriodResidentialCount
		dataType: int64
		formatString: 0
		lineageTag: 6a3d18f0-8433-4bf2-afa5-cb602e95f058
		summarizeBy: sum
		sourceColumn: PeriodResidentialCount

		annotation SummarizationSetBy = Automatic

	column PermitShare
		dataType: double
		lineageTag: a4bfca56-6c71-4643-b660-8981106ce50f
		summarizeBy: sum
		sourceColumn: PermitShare

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BaselinePeriod
		dataType: string
		lineageTag: 35933a9d-b088-4b40-9978-9bb3645a63f4
		summarizeBy: none
		sourceColumn: BaselinePeriod

		annotation SummarizationSetBy = Automatic

	column BaselinePermitCount
		dataType: int64
		formatString: 0
		lineageTag: 399108da-0919-4d42-9648-a2e0cbd112df
		summarizeBy: sum
		sourceColumn: BaselinePermitCount

		annotation SummarizationSetBy = Automatic

	column AbsoluteChange
		dataType: int64
		formatString: 0
		lineageTag: 2f39dbc9-683f-4e14-9566-9c0213b2cb18
		summarizeBy: sum
		sourceColumn: AbsoluteChange

		annotation SummarizationSetBy = Automatic

	column PercentChange
		dataType: double
		lineageTag: 60141a91-815c-453f-98b9-22d781a0fd73
		summarizeBy: sum
		sourceColumn: PercentChange

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SmallBaselineWarning
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 940c91e7-6e93-4e70-979a-744238180fb7
		summarizeBy: none
		sourceColumn: SmallBaselineWarning

		annotation SummarizationSetBy = Automatic

	partition ward_summary = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\alber\PycharmProjects\Data110_DP_Activity\data\processed\development_permits_residential_workbook.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "ward_summary", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type text}, {"Ward", Int64.Type}, {"IsMissingGeography", type logical}, {"PermitCount", Int64.Type}, {"PeriodResidentialCount", Int64.Type}, {"PermitShare", type number}, {"BaselinePeriod", type text}, {"BaselinePermitCount", Int64.Type}, {"AbsoluteChange", Int64.Type}, {"PercentChange", type number}, {"SmallBaselineWarning", type logical}}, "en-US")
				in
				  #"Changed column type"

